### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by phonoarchive** [vsespb/mt-aws-glacier#104]
Hello!

I've used mt-aws-glacier for 4 months and didn't have any problems, but recently I've got this:

Can't locate JSON/XS.pm in @INC (@INC contains: /home/sorokin/glacier/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /home/sorokin/glacier/lib/App/MtAws/LineProtocol.pm line 30.
BEGIN failed--compilation aborted at /home/sorokin/glacier/lib/App/MtAws/LineProtocol.pm line 30.
Compilation failed in require at /home/sorokin/glacier/lib/App/MtAws/ParentWorker.pm line 28.
BEGIN failed--compilation aborted at /home/sorokin/glacier/lib/App/MtAws/ParentWorker.pm line 28.
Compilation failed in require at /home/sorokin/glacier/lib/App/MtAws.pm line 45.
BEGIN failed--compilation aborted at /home/sorokin/glacier/lib/App/MtAws.pm line 45.
Compilation failed in require at ./mtglacier line 4.
BEGIN failed--compilation aborted at ./mtglacier line 4.

Could you give me any advise?
Many thanks,
Nikita

**Comment by vsespb** [comment]
It seems you don't have JSON::XS module, not sure how it worked before. It could not work without it. Probably module is gone missing on your system (not sure how and why).

FYI Install instructions: https://github.com/vsespb/mt-aws-glacier#installationsystem-requirements

**Comment by phonoarchive** [comment]
Yes, strangely it is gone, but I've restored this module, now everything works fine. Sorry for disturbing!
