### ISSUE TITLE
Not able to find retrieved file 

### ISSUE THREAD

**Issue by abhishek6590** [vsespb/mt-aws-glacier#107]
HI,

I retrieved a file from glacier and it is showing - 
PID 14745 Started worker
PID 14746 Started worker
PID 14747 Started worker
PID 14748 Started worker
PID 14745 Retrieved Archive N7gnLZujoKlhMftu0e8tQJxFLuWdkOhKIzA9mMBgejnAGBLV-4DcExFXNYl3IY1dX99vlqPwacBPNOEutIyEn5205zS7e0juFvt_pTwStQzkqcSON_wJWlWmceb7wISdEwBc81LA6g
OK DONE 

But I am not able to find my file in my dir. Does it take to for retrieval. Please help me to find out it.

Thanks

**Comment by vsespb** [comment]
Hi. Amazon requires you to first RETRIEVE the file, then wait 4h and download it within 24h . So you need run another command https://github.com/vsespb/mt-aws-glacier#restore-completed

**Comment by abhishek6590** [comment]
HI,

Thanks for replying. So i need to wait for 4h and then run the following command -
./mtglacier restore-completed --config glacier.cfg  --dir directory name  --filter '+filename -' --vault vaultname  --journal journal.log --max-number-of-files 1

Is it right ?

**Comment by vsespb** [comment]
looks right

**Comment by abhishek6590** [comment]
Thank You. I will do that.
