### ISSUE TITLE
Replicate rsync --delete behavior with mt-aws-glacier

### ISSUE THREAD

**Issue by qugu** [vsespb/mt-aws-glacier#108]
Hello Victor,
This is a usage help request rather than a issue.
I would like to use mt-aws-glacier as i use `rsync --delete` on my photo archive (sync changes, remove redundant/old files on amazon glacier). I understand that i cannot just remove a remote file.
I cannot figure out how I could archieve that behavior. I am now using:

 `/usr/bin/mtglacier sync --new --delete-removed --replace-modified --detect mtime-or-treehash --config=/path/glacier.cfg --dir=/media/files/pictures/ --vault=photo_arch --journal=/path/photo_arch_journal.log --journal-encoding=UTF-8 --concurrency=4`

Does that do what i'm trying to archieve?
Thank you.

**Comment by vsespb** [comment]
This looks good to me. `--delete-removed` will remove remote file if it's gone from local filesystem. Command looks ok. 

Note that you can use `--dry-run` when testing command to see how it will work.

**Comment by qugu** [comment]
Very good. Thank you.
