### ISSUE TITLE
-bash: ./mtglacier: No such file or directory

### ISSUE THREAD

**Issue by backendoadmin** [vsespb/mt-aws-glacier#109]
Hello,

I installed mt-aws-glacier without error, and then i added glacier.cfg with my creditentals, but it's not working. 

I got this error:
-bash: ./mtglacier: No such file or directory

I tried to connect to this value with a windows client, and it worked. 

Do you have any idea, what can i do wrong?

**Comment by vsespb** [comment]
Hello.

If yo've used manual installation https://github.com/vsespb/mt-aws-glacier#manual-installation then file `mtglacier` should be in current directory.

Other installation ways install `mtglacier` into one of PATH directories.

So run `mtglacier` (not `./mtglacier`) if yo've used other ways than manual install.

Indeed, all examples in manual are with `./mtglacier` , that can be confusing..

**Comment by backendoadmin** [comment]
Thank you, it's work. I have to use mtglacier command.

**Comment by backendoadmin** [comment]
Sorry, maybe i was to fast. 

I can create new vault, but the uploaded file doesn't show up.

pi@raspberrypi ~ $ mtglacier sync --config glacier.cfg --dir /home/pi/backup/ --vault myvault --journal journal.log --concurrency 3
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.120

PID 3005 Started worker
PID 3006 Started worker
PID 3007 Started worker
Skip test.txt
PID 3007 Created an upload_id oNWNEtFynD2bA21_5Q-e7hMcQCWUywac_bmaoNp0HoX-qMDopSIfX_fFPkembCvDdpLpBUDKuXJ64pBw9ZQ4FaaXQySd
PID 3005 Uploaded part for new.txt at offset [0]
PID 3006 Finished new.txt hash [7aa7a5359173d05b63cfd682e3c38487f3cb4f7f1d60659fe59fab1505977d4c] archive_id [6txA1FbhhUTFJyONGgd9dAnG1XfmmAi9IgipOD0AYZOz4tLwK3pD83KYrltI7EO_Xqs5J4_u9pfbvIO-a5f0pBvs9KIeVpNElHee2KGoo5XgtOZLrEeGVDqlA5Dd--2xQlNuipOjVg]
OK DONE

**Comment by vsespb** [comment]
> but the uploaded file doesn't show u

where you expect to see it ?

**Comment by backendoadmin** [comment]
https://console.aws.amazon.com/glacier/home?region=eu-central-1

myvault Not updated yet -- --
sfbackup Not updated yet -- --

and i dont see through fastglacier wiin client too. 

Or is it working fine? How can i verify successfully upload?

and i gues it's wrong because after offset i saw [0], but maybe it's some other thing.

**Comment by vsespb** [comment]
Those figures updated once 24 hours

**Comment by backendoadmin** [comment]
Sorry, i can wait. Thank you.

**Comment by vsespb** [comment]
So, was it working? Can we close the issue?
