### ISSUE TITLE
File::Path does not export make_path on CentOS 5.8

### ISSUE THREAD

**Issue by funjon** [vsespb/mt-aws-glacier#11]
On a CentOS 5.8 machine:

[root@host mt-aws-glacier]# perl -cw mtglacier.pl 
"make_path" is not exported by the File::Path module
Can't continue after import errors at ChildWorker.pm line 28
BEGIN failed--compilation aborted at ChildWorker.pm line 28.
Compilation failed in require at mtglacier.pl line 35.
BEGIN failed--compilation aborted at mtglacier.pl line 35.

It looks like CentOS boxes come with File::Path v1.08, and make_path is from v2.0.  I suspect the answer I'll get it "upgrade File::Path", but I wanted to see if there was a better workaround.

**Comment by vsespb** [comment]
Thanks for reporting this! I will check what can be done here..

**Comment by vsespb** [comment]
Yes, I can confirm that CentOS 5.8 comes with File::Path v1.08, which does not support make_path.
There is old "legacy" method "mkpath" exists in File::Path and I can use it.

So I will fix that and do a release today or tomorrow.

**Comment by vsespb** [comment]
Done, fixed in v0.77beta

**Comment by funjon** [comment]
Awesome, thanks!
