### ISSUE TITLE
retrieve and download in one operation

### ISSUE THREAD

**Issue by p53** [vsespb/mt-aws-glacier#111]
Hi,

i think it would be useful if retrieve and download operations would be in one operation. After retrieve script would be waiting and polling for job status and aftere completition of retrieve operation automatically download, you know when i start retrieve operation when i am leaving job i don't want to get up in the evening just to issue download command altough of course i can write script for that

**Comment by vsespb** [comment]
Well, maybe yes.
However doing it with scripting as simple as writing retrieve command with same options, that were used to retrieve. And inserting sleep 4h between it.

**Comment by p53** [comment]
I haven't used glacier yet, i am now investigating it, but as i read in AWS docs it might be 4+ hours, so job completition time is unknown, so i have to also poll for job status and parse output, anyway thanks for answer
