### ISSUE TITLE
delete operation enhance

### ISSUE THREAD

**Issue by p53** [vsespb/mt-aws-glacier#112]
maybe it would be useful also have more advanced delete operation, e.g. delete on pattern/createdate etc..

**Comment by vsespb** [comment]
hi. `sync` with `--delete-removed` with https://github.com/vsespb/mt-aws-glacier#file-selection-options
will allow deletion by file pattern (only file missed from local filesystem)

`purge-vault` with https://github.com/vsespb/mt-aws-glacier#file-selection-options allows deletion by file pattern as well
