### ISSUE TITLE
Question: Is there a reason concurrency is capped at 30?

### ISSUE THREAD

**Issue by CaptSpify** [vsespb/mt-aws-glacier#116]
Is there a reason concurrency is capped at 30? I'm needing to run more than 30 instances, and want to see if there's a reason I can't just arbitrarily up the limit?

Thanks

**Comment by vsespb** [comment]
Probably no reason. Try raise in ConfigDefinition.pm

**Comment by CaptSpify** [comment]
Yup, works like a charm. Thanks
