### ISSUE TITLE
List Archives

### ISSUE THREAD

**Issue by MorganCloud** [vsespb/mt-aws-glacier#120]
Hello, 

Is it possible to list the uploaded content and get the names instead of the ID?

**Comment by vsespb** [comment]
Hello.

file names are in journal file (in plaintext; together with other data) (and if you lost your journal file you can restore it https://github.com/vsespb/mt-aws-glacier#restoring-journal  )

**Comment by AmorganICUC** [comment]
Thank you , well I meant I want a list of content currently stored in glacier, because it could've been uploaded, but since deleted.

**Comment by MorganCloud** [comment]
thank you

**Comment by vsespb** [comment]
same way: first restore journal https://github.com/vsespb/mt-aws-glacier#restoring-journal , next you have the list in journal
