### ISSUE TITLE
downloading from synced directory

### ISSUE THREAD

**Issue by MorganCloud** [vsespb/mt-aws-glacier#121]
Hello, 

I have search previous questions but not seen anyone ask, so I apologize if some has asked before. Can I download a single file? I have synced a directory of tar.gz log files and would like to test recovery before deleting them in house. Is it possible to download single files?

thank you

**Comment by MorganCloud** [comment]
I already did :
**mtglacier download-inventory --config=glacier.cfg  --new-journal=text-journal.log**
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.120
PID 1034 Started worker
PID 1034 Fetched job list for inventory retrieval
OK DONE

**Comment by vsespb** [comment]
hi
see https://github.com/vsespb/mt-aws-glacier#usage
see `restore` `restore-completed` commands
for file selection see 
https://github.com/vsespb/mt-aws-glacier#file-selection-options

i.e. you need to select a single file with file selection options, and then `restore` it, and then when Amazon restores it, download it with `restore-completed`

**Comment by MorganCloud** [comment]
ok, so I did the following :+1: 
mtglacier download-inventory --config=glacier.cfg --filter 'logstash-2016.04.09.tar.gz' --new-journal download.journal

So I wait 4hrs, then it becomes available , the use the retrieve command?

**Comment by vsespb** [comment]
not `download-inventory` but `restore` (assuming you already have fresh inventory, previously downloaded with download-inventory), and filter probably `'+logstash-2016.04.09.tar.gz -'`, and it'll also ask max-number-of-files

**Comment by MorganCloud** [comment]
ok, so I should first 
**mtglacier restore --config=glacier.cfg --filter '+logstash-2016.04.09.tar.gz' --new-journal download.journal**
then 
**mtglacier restore-completed --config=glacier.cfg --filter '+logstash-2016.04.09.tar.gz' --new-journal download.journal**

**Comment by vsespb** [comment]
there is a minus sign after filename in filter. pls read manual carefully, otherwise it could do wrong thing, very exprensive wrong thing

**Comment by MorganCloud** [comment]
ahh, ok , thank you 

so I did :+1: 
**mtglacier restore --config=glacier.cfg --filter '+logstash-2016.04.09.tar.gz -' --dir download --max-number-of-files 1**

and got 
PID 20513 Started worker
PID 20514 Started worker
PID 20515 Started worker
PID 20516 Started worker
PID 20513 Retrieved Archive m7YWvQicGvDII8NHA4g8z4qkF-PXOB9AI3OgNhUP7pWi4aNfV693DTZPcKN553fXb6JOnEZ-tN17Kwj-pRHLYNe**yTD3yVAacz-uveKq_8Sw
OK DONE

, so now wait 4 hrs then:

**mtglacier restore-completed --config=glacier.cfg --filter '+logstash-2016.04.09.tar.gz -' --new-journal download.journal**
