### ISSUE TITLE
Sync resume?

### ISSUE THREAD

**Issue by mbevilacqua** [vsespb/mt-aws-glacier#124]
This is really a question but probably an enhancement request as I'd guess it would be documented if supported.
When using sync on large files that get split for upload by mt-aws-glacier if we have to kill the sync process and restart it will uploaded segments be re-uploaded or will it resume uploading from the last segment successfully uploaded?

**Comment by vsespb** [comment]
if you kill process, it will start uploading from scratch. maybe try pause process (Ctrl-S, Ctrl-Q)?
I think there is existing ticket for the enhancement https://github.com/vsespb/mt-aws-glacier/issues/62

**Comment by mbevilacqua** [comment]
I'll probably approach it the same way as #62 and split files then.
Thanks for that quick reply, keep up the great work!
