### ISSUE TITLE
Error While Uploading file to Galcier

### ISSUE THREAD

**Issue by IndrajithS** [vsespb/mt-aws-glacier#131]
Hi,
I use mt-aws-glacier master to upload a file 14GB to Glacier but the uploading process STOP with the following error messages.
![screenshot from 2017-07-27 17 30 54](https://user-images.githubusercontent.com/15086359/28669334-875347e0-72f1-11e7-98e7-0847a96379b1.png)

Thanks for your support!

**Comment by vsespb** [comment]
hi.
i need

1. `perl -MDigest::SHA -E 'say Digest::SHA->VERSION'`
2. `perl -V ` (note capital V)
3. your OS and distro version
4. `mtglacier --version`
5. is the error intermittent or 100% reproducible. happens how often?
6. plz test your RAM with http://manpages.ubuntu.com/manpages/xenial/man8/memtester.8.html

similar issue here https://github.com/vsespb/mt-aws-glacier/issues/105#issuecomment-317241673

btw by chance are you and https://github.com/pqkhanhvn different persons?

**Comment by IndrajithS** [comment]
Hi,
Here by i am attaching the file which provide the details you asked.
While uploading 5 files with same size (15 GB) one file get uploaded and other  4 files get the same error which specified above.
I am an different person!
[Error_log.txt](https://github.com/vsespb/mt-aws-glacier/files/1182581/Error_log.txt)



Thanks

**Comment by IndrajithS** [comment]
Hi,
Thanks for the reply. The error is due to network issue.

**Comment by vsespb** [comment]
hi, thx for updating. could you pls describe what exactly was the problem with your network? it might help troubleshot similar issue https://github.com/vsespb/mt-aws-glacier/issues/105

**Comment by rmallah** [comment]
Hi Victor , thanks for the reply . 
I am interested in debugging the issue.  
I will give this problem some time . When you have time please give some generic
pointers. I write programs in perl and i am happy to see this program.

**Comment by vsespb** [comment]
@rmallah, you answered in wrong ticket. your is here: https://github.com/vsespb/mt-aws-glacier/issues/134 - and we're not about debugging something yet. pls read my last reply.
