### ISSUE TITLE
sync to Glacier from a cifs share results in 90% of the files being skipped

### ISSUE THREAD

**Issue by PaoloRipa** [vsespb/mt-aws-glacier#132]
Hello,
I am trying to sync from a cifs share to a glacier vault and running the tool results in only 9 of ~6000 files to be actually synced:
`mtglacier check-local-hash --config /home/oper/glacier.d/mtAwsGlacier.conf --dir /home/oper/data --journal /home/oper/glacier.d/glacierJournal/testVault_journal.log
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.120
...
TOTALS:
9 OK
0 MODIFICATION TIME MISSMATCHES
0 TREEHASH MISSMATCH
0 SIZE MISSMATCH
0 ZERO SIZE
5730 MISSED
0 ERRORS
ERROR: check-local-hash reported errors`

The command I am using to sync is the following:
`mtglacier sync --config /home/oper/glacier.d/mtAwsGlacier.conf --dir /mnt/paolo --vault paoloBkp --journal /home/oper/glacier.d/glacierJournal/paoloBkp_journal.log --concurrency 10 --leaf-optimization 0`

Why is the sync skipping basically all my files?

Thanks.

**Comment by vsespb** [comment]
Hi. Did you read "MUST READ" section? https://github.com/vsespb/mt-aws-glacier#warnings--must-read-

**Comment by PaoloRipa** [comment]
Hello,
I did and I set the leaf-optimisation to 0. Still I can't understand what I am doing wrong.
Those files and dirs are not zero sized/empty, that's for sure...
A hint would be appreciated :-)

Cheers.

**Comment by vsespb** [comment]
hm, then it's me who did not read the issue description)

I see `--dir` for check-local-hash and sync are different. try set same? also try run `sync` with `--dry-run` and see output which files it uploads which skips?

and use `leaf-optimisation=0` when check-local-hash also!

**Comment by PaoloRipa** [comment]
Hello again and thanks for your support.
So, check-local-hash - apparently - does not support leaf-optimisation flag:
mtglacier check-local-hash --config /home/oper/glacier.d/mtAwsGlacier.conf --dir /mnt/paolo --journal /home/oper/glacier.d/glacierJournal/testVault_journal.log --leaf-optimization 0
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.120

ERROR: Unexpected option "--leaf-optimization"

I tested again the check-local-hash with the correct directory (silly of me, sorry!):
mtglacier check-local-hash --config /home/oper/glacier.d/mtAwsGlacier.conf --dir /mnt/paolo --journal /home/oper/glacier.d/glacierJournal/testVault_journal.log 
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.120

...
TOTALS:
9 OK
0 MODIFICATION TIME MISSMATCHES
0 TREEHASH MISSMATCH
0 SIZE MISSMATCH
0 ZERO SIZE
0 MISSED
0 ERRORS
OK DONE

Weird thing is I see only 9 files and none MISSED, but when I do the dry run and grep the output for "Skip":

mtglacier sync --config /home/oper/glacier.d/mtAwsGlacier.conf --dir /mnt/paolo --vault paoloBkp --journal /home/oper/glacier.d/glacierJournal/paoloBkp_journal.log --concurrency 10 --leaf-optimization=0 --dry-run | grep Skip | wc -l
5683

Almost 6000 items are skipped.

**Comment by vsespb** [comment]
ok, indeed check-local-hash does not accept leaf-optimization as it does not traverse dir.

1) i see in above output "journal" are different: /home/oper/glacier.d/glacierJournal/paoloBkp_journal.log and /home/oper/glacier.d/glacierJournal/testVault_journal.log

2) try wc -l journalfile

**Comment by PaoloRipa** [comment]
I need to get coffee before testing and stop relying on bash aliases for long command.
I was using a wrong journal, as you pointed out, from an old test. 
When I use the proper journal, I can see all items have been synced to my vault.
Many apologies for wasting your time, Victor.

Thanks so much for your help and for writing this great piece of software, man!!!

Ciao.
Paolo
