### ISSUE TITLE
connection problem when using https

### ISSUE THREAD

**Issue by falk0069** [vsespb/mt-aws-glacier#133]
I'm seeing this error when using https:
`PID 29420 HTTP connection problem (timeout?). Will retry (0 seconds spent for request)`

Here is the command I'm running
`mtglacier sync --config /root/glacier.cfg --dir /data/backup --vault test2 --journal /root/glacier_test2.log --concurrency 4`

And I have this set in the glacier.cfg
`protocol=https`

I added a few lines to GlacierRequest.pm to further debug:
```
use Data::Dumper;
print Dumper($resp);
```

This is what I get (few lines masked):
```
$VAR1 = bless( {
                 '_content' => 'Can\'t connect to glacier.us-east-1.amazonaws.com:443

',
                 '_rc' => 500,
                 '_headers' => bless( {
                                        'client-warning' => 'Internal response',
                                        'client-date' => 'Sun, 03 Sep 2017 05:09:34 GMT',
                                        'content-type' => 'text/plain',
                                        '::std_case' => {
                                                          'client-warning' => 'Client-Warning',
                                                          'client-date' => 'Client-Date'
                                                        }
                                      }, 'HTTP::Headers' ),
                 '_msg' => 'Can\'t connect to glacier.us-east-1.amazonaws.com:443',
                 '_request' => bless( {
                                        '_content' => '',
                                        '_uri' => bless( do{\(my $o = 'https://glacier.us-east-1.amazonaws.com/-/vaults/test2/multipart  -uploads')}, 'URI::https' ),
                                        '_headers' => bless( {
                                                               'user-agent' => 'mt-aws-glacier/1.120 (http://mt-aws.com/) libwww-perl/6  .26',
                                                               'x-amz-part-size' => 16777216,
                                                               'x-amz-date' => '20170903T050934Z',
                                                               'authorization' => 'AWS4-HMAC-SHA256 Credential=AKI**************201  70903/us-east-1/glacier/aws4_request, SignedHeaders=host;x-amz-archive-description;x-amz-date;x-amz-glacier-version;x-amz-part-size, Signature=34f**********************************************************7a2',
                                                               '::std_case' => {
                                                                                 'x-amz-part-size',
                                                                                 'x-amz-date' => 'X-Amz-Date',
                                                                                 'x-amz-glacier-version' => 'X-Amz-Glacier-Version',
                                                                                 'x-amz-archive-description' => 'X-Amz-Archive-Description'
                                                                               },
                                                               'host' => 'glacier.us-east-1.amazonaws.com',
                                                               'x-amz-glacier-version' => '2012-06-01',
                                                               'x-amz-archive-description' => 'mt2************************************************************************In0'
                                                             }, 'HTTP::Headers' ),
                                        '_method' => 'POST'
                                      }, 'HTTP::Request' )
               }, 'HTTP::Response' );
```

If I switch it to `protocol=http`, then it works.

Any ideas why I might be getting a 500 error when using https?

**Comment by vsespb** [comment]
hi. it looks like your network or Amazon's fault. why not?

**Comment by falk0069** [comment]
I've been debugging a bit more and discovered via tcpdump that the client is disconnecting due to Alert-21 message-48: 'Unknown CA'.   So tried hard coding this in the code:  ``SSL_verify_mode=>0``.  That made no difference, so I switched it back.  I then tried hard coding this:  ``verify_hostname => 0``.  THAT DID IT!  But I don't understand it.  

From what I understand all this is doing is making sure the host I'm connecting to is the same host that is in the certificate.   In my debug output I see this:
`` 'client-ssl-cert-subject' => '/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=glacier.us-east-1.amazonaws.com'``
``'host' => 'glacier.us-east-1.amazonaws.com'``

It looks like a match to me.  Why would it be bombing out?  

In either case, I'm getting closer.  Hopefully, I'll figure out what is going on.  Let me know if you have any thoughts.

**Comment by falk0069** [comment]
Well, the issue seems to be either with Amazon or LWP.  I've been digging into LWP and the various verification schemes and whatnot but not getting very far.  I can reproduce the issue with very simple script:
```
#!/usr/bin/perl

use LWP::UserAgent;
use Data::Dumper;

$ua = LWP::UserAgent->new(ssl_opts => { verify_hostname => 1 });
$res = $ua->get("https://glacier.us-east-1.amazonaws.com");
  
print Dumper($res);
```

The issue only happens when hitting that URL. Using different URLs work fine.  I even found out that **east-2** works! 

So, I'll just move to east-2 instead.  And if the same issue starts happening to east-2, I'll use your FAKE_HOST workaround to get up and running quickly (but use the real hostname).  Something like this:
`MTGLACIER_FAKE_HOST="glacier.us-east-1.amazonaws.com" mtglacier create-vault test2 --config glacier.cfg`

Do let me know if you have any thoughts or suggestions.

Thanks!

**Comment by vsespb** [comment]
The above script works fine for me:
```
$VAR1 = bless( {
                 '_request' => bless( {
                                        '_uri' => bless( do{\(my $o = 'https://glacier.us-east-1.amazonaws.com')}, 'URI::https' ),
                                        '_method' => 'GET',
                                        '_uri_canonical' => bless( do{\(my $o = 'https://glacier.us-east-1.amazonaws.com/')}, 'URI::https' ),
                                        '_headers' => bless( {
                                                               '::std_case' => {
                                                                                 'if-ssl-cert-subject' => 'If-SSL-Cert-Subject'
                                                                               },
                                                               'user-agent' => 'libwww-perl/6.15'
                                                             }, 'HTTP::Headers' ),
                                        '_content' => ''
                                      }, 'HTTP::Request' ),
                 '_content' => '{"code":"MissingParameterValueException","message":"Required parameter missing: API version","type":"Client"}',
                 '_headers' => bless( {
                                        'connection' => 'close',
                                        'client-ssl-cert-subject' => '/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=glacier.us-east-1.amazonaws.com',
                                        'x-amzn-requestid' => 'Bz2Au4DEqFuEtVS8AOItYrC1nHH5Q-b5sjQ1nasqq9xGP_4',
                                        'client-ssl-cipher' => 'ECDHE-RSA-AES128-SHA',
                                        'client-response-num' => 1,
                                        'client-ssl-socket-class' => 'IO::Socket::SSL',
                                        'client-peer' => '54.239.30.220:443',
                                        '::std_case' => {
                                                          'client-ssl-cipher' => 'Client-SSL-Cipher',
                                                          'client-response-num' => 'Client-Response-Num',
                                                          'client-peer' => 'Client-Peer',
                                                          'client-ssl-socket-class' => 'Client-SSL-Socket-Class',
                                                          'client-ssl-cert-issuer' => 'Client-SSL-Cert-Issuer',
                                                          'client-date' => 'Client-Date',
                                                          'client-ssl-cert-subject' => 'Client-SSL-Cert-Subject',
                                                          'x-amzn-requestid' => 'X-Amzn-RequestId'
                                                        },
                                        'client-ssl-cert-issuer' => '/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4',
                                        'date' => 'Sun, 03 Sep 2017 20:36:15 GMT',
                                        'content-length' => '109',
                                        'client-date' => 'Sun, 03 Sep 2017 20:36:19 GMT'
                                      }, 'HTTP::Headers' ),
                 '_protocol' => 'HTTP/1.1',
                 '_rc' => '400',
                 '_msg' => 'Bad Request'
               }, 'HTTP::Response' );
```
what's your version of perl, LWP::UserAgent, IO::Socket::SSL, Mozilla::CA ? Try updating Mozilla::CA maybe.

**Comment by falk0069** [comment]
Looks like my IO::Socket::SSL is NOT up to date.  That perhaps might be it.  I'm in the middle of a large upload right now, but I will try upgrading that afterwards (tomorrow) and see if that fixes it.  It is good to know that the script works for you.  But so strange how east-1 fails but east-2 works for me.

Here are my version:

root@knoppmyth:~$ perl --version
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 34 registered patches, see perl -V for more detail)

root@knoppmyth:~# cpan -D LWP::UserAgent | egrep "Installed|CPAN"
Loading internal null logger. Install Log::Log4perl for logging messages
        Installed: 6.26
        CPAN:      6.26  up to date
		
root@knoppmyth:~# cpan -D IO::Socket::SSL | egrep "Installed|CPAN"
Loading internal null logger. Install Log::Log4perl for logging messages
        Installed: 1.94
        CPAN:      2.050  Not up to date
		
root@knoppmyth:~# cpan -D Mozilla::CA | egrep "Installed|CPAN"
Loading internal null logger. Install Log::Log4perl for logging messages
        Installed: 20160104
        CPAN:      20160104  up to date

I'll let you know.  Thanks for the advice.

**Comment by falk0069** [comment]
I updated the IO::SocketSSL to 2.050 but the problem continues to happen.   I also noticed that for west-1 and west-2 I have the same issue.  I am so baffled.  If I can get to the bottom of this, I'll let you know so you can add it to your requirements section (if warranted).

**Comment by falk0069** [comment]
okay...I figured out the difference/issue.  Long story short I **believe** AWS will fix the issue next month.  The certificate for east-1, west-1, west-2 all expire early October.  The Cert for East-2 was just renewed in July (the working one).  

So, what I did is I ran my mini script from earlier and prefixed this in front: ``perl -MIO::Socket::SSL=debug30``.  This allowed the SSL module to print extra debug info.  This is what got printed when hitting a **failing** one:
```
DEBUG: .../IO/Socket/SSL.pm:2659: ok=0 [2] /C=US/O=VeriSign, Inc./OU=Class 3 Public Primary Certification Authority/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
DEBUG: .../IO/Socket/SSL.pm:789: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:792: SSL connect attempt failed
```

This is what I saw with a **working** one:
```
DEBUG: .../IO/Socket/SSL.pm:2659: ok=1 [2] /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
DEBUG: .../IO/Socket/SSL.pm:2659: ok=1 [1] /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
DEBUG: .../IO/Socket/SSL.pm:2659: ok=1 [0] /C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=glacier.us-east-2.amazonaws.com
DEBUG: .../IO/Socket/SSL.pm:1723: scheme=default cert=19902480
DEBUG: .../IO/Socket/SSL.pm:1733: identity=glacier.us-east-2.amazonaws.com cn=glacier.us-east-2.amazonaws.com alt=2 glacier.us-east-2.amazonaws.com
DEBUG: .../IO/Socket/SSL.pm:789: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:799: ssl handshake in progress

```

The **working** one I could see the all the certificates in the chain and they match what I see when comparing to a browser.

The **failing** on the other hand only contained the root cert and it was **incorrect**.  It basically said the root cert was signed by ``Class 3 Public Primary Certification Authority`` instead of ``VeriSign Class 3 Public Primary Certification Authority - G5``.  

When I compare the cert chain in a browse all sites have the same chain, so I was baffled.  I then ran a tcpdump to inspect the certificate exchange.  What I had discovered is for east-1/west-1/west-2 they all are supplying the **incorrect** root certificate.  East-2 on the other hand is only supplying the certificate and the intermediate certificate.  It does not supply the root certificate in the chain.  Also, as mentioned earlier, east-2 recently renewed their cert.

So, I don't fully understand the certificate exchange chain and how root certs get updated, but there is something to do with it going on.  I'm guessing I might be missing some CA (or have an updated one) in my CA bundle and that is why it is failing for me.  I played around with downloading a new cacert.pem and manually edited it, but wasn't successful.  I'm hopefully that when AWS upgrades their cert for the other sites, they will no longer supply the root cert and everything will start working.

So, I don't think there is anything you need to worry about except to be aware that some folks might run into this issue.  I can follow up one last time next month to verify if it is resolved or not for me.

Thanks!

**Comment by falk0069** [comment]
Sorry one more comment...I found a stackoverflow discussion that explains it better:
[https://stackoverflow.com/questions/30554222/perl-lwp-certificate-verify-failed-with-paypal-com/30554531#30554531](url)

Basically:

-------------------------------------------------
Since 1024 bit certificates where removed by Mozilla end of last year you will not find them in the current Mozilla::CA any longer. But browsers don't need the old certificate because the create the trust chain based on certificates [0] and [1] already because they use a built-in certificate instead of the certificate [2] send by the server.

While this newer built-in certificate is also included in Mozilla::CA it will not be used because of a long-standing bug in how OpenSSL validates certificates: it will always try to validate the longest chain and not check if a shorter chain is possible.

------------------------------------------------------------

So, I feel more confident that it will be fixed in a month or so and there is no need to try and load in the older 1024 certs to make it work.

Thanks for creating this wonderful software.  I've been successful at uploading about 50G of photos/videos so far.  FYI, I was using Crashplan, but they stopped supporting home users.  This will be much better and cheaper.

**Comment by vsespb** [comment]
Impressive investigation! Thanks. I will close for now
