### ISSUE TITLE
Question: MTIME missmatch

### ISSUE THREAD

**Issue by PaoloRipa** [vsespb/mt-aws-glacier#137]
Dear Victor,
while inspecting the result of a check-local-hash on a backup set of mine, I run into some files being marked with a modification time mismatch.
I checked the source code (CheckLocalHash.pm) and - with my level of knowledge of perl - I think this status is encountered when the actual mtime of a file is different from the one in the journal file.
Is my understanding correct?
If so, does this mean that the file is a candidate for being pushed to the vault next time sync is run on that particular directory, or does the mtime mismatch imply some sort of issue?

Thanks,
keep up the wonderful work you are doing!

Paolo Ripamonti

**Comment by vsespb** [comment]
>  is encountered when the actual mtime of a file is different from the one in the journal file

exactly. 

> If so, does this mean that the file is a candidate for being pushed to the vault next time sync is run on that particular directory,

yes, exaclty. (`sync` with `--replace-modified` and appropriate `--detect` option)

> does the mtime mismatch imply some sort of issue?

no.
