### ISSUE TITLE
getting 403 when trying to sync files/running cycletest.sh

### ISSUE THREAD

**Issue by shekarkcb** [vsespb/mt-aws-glacier#2]
When i run the script with glacier.cfg, i am getting below message - 
command run is - `time perl mtglacier.pl sync --config=./glacier.cfg --from-dir backups/ --to-vault=mytestvault --journal=journal.log  --concurrency=3`
and the response was , 
`{"message":"Signature expired: 20120907T094027Z is now earlier than 20120907T094737Z (20120907T095237Z - 5 min.)","code":"InvalidSignatureException","type":"Client"}`

Thanks.

**Comment by vsespb** [comment]
Hello. Sorry for late response, somehow I did not received email notification for this issue.

Amazon needs a timestamp for each request. This message means request time differs from real time a lot.
Most common reason for this is that your system clock is not accurate. Also make sure your timezone is correct.

**Comment by shekarkcb** [comment]
Thanks for the reply. 
When i run the date command on the machine, its giving below output.
cmd  - `date` => o/p `Mon Sep 10 10:59:12 IST 2012` , Is there any way to check my dat/timezone is correctly configured to take care of aws?

Thanks.

**Comment by vsespb** [comment]
You can use sites like http://time.is/ to check your time. Or you can ask any of your friends for correct time. Make sure "IST" is correct timezone for your location. Under linux you can synchronize time using NTP software.

Also, seems you are newbie in linux, so I must warn you - before using Amazon Glacier make sure you understand their pricing model - retrieving data back can be extremely expensive http://aws.amazon.com/glacier/faqs/#How_will_I_be_charged_when_retrieving_large_amounts_of_data_from_Amazon_Glacier

**Comment by shekarkcb** [comment]
I think, the issue was with my time, it was behind 10mins from actual time of India - i corrected the same and now i can see mtglacier script working. Thanks for pointing out.

Thanks.
