### ISSUE TITLE
Problem with credentials

### ISSUE THREAD

**Issue by bembol** [vsespb/mt-aws-glacier#22]
Hi There,

I'm getting this strange error with credential issues. I don't know why as my key and secret codes are fine already  tested them on different glacier uploader. 

I put my credentials in glacier.cfg file like manual said.

key=1111111/222222/333333/44444444444/5
secret=xxxxxxxxxxxxxxxxxxxxxxxx

Any suggestions would be very useful.

Below log file.

MT-AWS-Glacier, Copyright 2012-2013 Victor Efimov http://mt-aws.com/ Version 0.86beta

PID 16829 Started worker
PID 16830 Started worker
PID 16831 Started worker
Error:
POST https://glacier.eu-west-1.amazonaws.com/-/vaults/test1/multipart-uploads
Authorization: AWS4-HMAC-SHA256 Credential=trXVr9de6W/ixgoCtC/L14hhJZ/WC5hIOCbc26/7/20130204/eu-west-1/glacier/aws4_request, SignedHeaders=host;x-amz-archive-description;x-amz-date;x-amz-glacier-version;x-am
z-part-size, Signature=e2b76702376e0a3fec67160f792b1261a40eed1077bddadd923a816
Host: glacier.eu-west-1.amazonaws.com
User-Agent: mt-aws-glacier/0.86beta (http://mt-aws.com/) libwww-perl/6.03
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
X-Amz-Archive-Description: mt2 eyJmaWxlbmFtZSI6ImRhdl9zd0LCJtdGltZSI6IjIjA0VDAzNTc1MVoifQ
X-Amz-Date: 20130204T120444Z
X-Amz-Glacier-Version: 2012-06-01
X-Amz-Part-Size: 16777216

(no content)
HTTP/1.1 403 Forbidden
Date: Mon, 04 Feb 2013 12:04:44 GMT
Content-Length: 248
Content-Type: application/json
Client-Date: Mon, 04 Feb 2013 12:04:45 GMT
Client-Peer: 178.236.6.231:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=Terms of use at https://www.verisign.com/rpa (c)10/CN=VeriSign Class 3 Secure Server CA - G3
Client-SSL-Cert-Subject: /C=US/ST=Washington/L=Seattle/O=Amazon.com Inc./CN=glacier.eu-west-1.amazonaws.com
Client-SSL-Cipher: RC4-MD5
Client-SSL-Socket-Class: IO::Socket::SSL
X-Amzn-RequestId: MFSGTawLvs1Lg2dl5o5rriJBc8Ph4nv-BI_nr8DbwQXBuZE

{"message":"Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got '1111111/222222/333333/44444444444/5/20130204/eu-west-1/glacier/aws4_request'","code":"Incom
pleteSignatureException","type":"Client"}

**Comment by vsespb** [comment]
Hello.
Do you really have '/' - slash characters in the key ? Is this some special key?

**Comment by vsespb** [comment]
According to doc KEY is 20 characters alphanumeric characters only, SECRET is 40 characters (usually contains '/')
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSGettingStartedGuide/AWSCredentials.html

Seems '/' is possible in SECRET only. So probably you swapped KEY and SECRET.

**Comment by vsespb** [comment]
BTW, Thus, I see part of your SECRET is visible above in your logs, and compromised. (there should be KEY, not SECRET). You can probably change it in Amazon console.

**Comment by bembol** [comment]
You were right. Now it works fine. I've already changed my Secret key.

Thank you for your help.

**Comment by vsespb** [comment]
ok, cool.

**Comment by naoufelfrioui** [comment]
hi, i have the same problem , how can i change the secret key ??
