### ISSUE TITLE
--exclude

### ISSUE THREAD

**Issue by funjon** [vsespb/mt-aws-glacier#23]
How hard would it be to tell mtglacier to exclude patterns from files to sync (or only include certain patterns).

Like if I want to do --include *.gz or --exclude access_log --exclude error_log.

**Comment by vsespb** [comment]
Currently this very useful feature is not implemented. Going to implement this month. Leaving ticket open for now.

**Comment by funjon** [comment]
ty!

**Comment by vsespb** [comment]
Done, v 0.936 beta, see `File selection options` in README https://github.com/vsespb/mt-aws-glacier#file-selection-options. Also `--dry-run` implemented - pretty useful when testing exclude patterns.
