### ISSUE TITLE
Warning generated when I run the code

### ISSUE THREAD

**Issue by raydude** [vsespb/mt-aws-glacier#27]
I'm new to the tool, but I wanted to figure out if this was a problem with my gentoo.

When I run the tool I get these two warnings:

server mt-aws-glacier # ./mtglacier
Prototype after '@' for App::MtAws::ConfigEngine::validation : @_ at lib/App/MtAws/ConfigEngine.pm line 320.
Prototype after '%' for App::MtAws::ConfigEngine::command : $%;$ at lib/App/MtAws/ConfigEngine.pm line 329.
MT-AWS-Glacier, Copyright 2012-2013 Victor Efimov http://mt-aws.com/ Version 0.88beta

I'm going to try the tool anyway, but if you have advice for how to fix this, I'd appreciate it.

Thanks,

Brian

**Comment by vsespb** [comment]
Hello.

Your Perl version ?

```
 perl -v
```

**Comment by raydude** [comment]
Thanks for the quick response!

server ~ # perl -v

This is perl 5, version 12, subversion 4 (v5.12.4) built for x86_64-linux-thread-multi
(with 12 registered patches, see perl -V for more detail)

**Comment by vsespb** [comment]
Ok, I reproduced a problem and fixed that in master branch. Version number same.
This was  just a warning message, not error.
I have Perl 5.10, and this new warning was added in Perl 5.12.

**Comment by vsespb** [comment]
and thanks for reporting this!
