### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by michelpereira** [vsespb/mt-aws-glacier#28]
I'm trying to recreate my journal.log file using the retrieve-inventory command, whey I run:
./mtglacier download-inventory --config=glacier.cfg --vault=Personal --new-journal=new-journal.log

it's giving me the output

DIE outside EVAL block [0]
Call stack: 
App::MtAws::main(./mtglacier:5)
App::MtAws::**ANON**(/Users/michelp/Dropbox/aws/glacier/mt-glacier/lib/App/MtAws.pm:309)
Fatal Error: 0 unexpected end of string while parsing JSON string, at character offset 139389 (before "(end of string)") at /Users/michelp/Dropbox/aws/glacier/mt-glacier/lib/App/MtAws.pm line 309, <GEN0> line 2.
### 

Perl version:

This is perl 5, version 12, subversion 4 (v5.12.4) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Thank you

**Comment by vsespb** [comment]
Hello. Hm. strange.

is this similar issue ? https://github.com/basak/glacier-cli/issues/12#issuecomment-10818195

Any success with other tools?
With what tool this vault was uploaded?
Your amazon region?

Could you please checkout `development` branch now, and run tool again.
it should create '_json.log' in _current_ directory before crash now with full JSON response, received from Amazon Glacier.

Then you can either.

(warning, it can contain sensetive information like filenames, file hashes and archive ids).
1. check if JSON is valid here http://jsonlint.com/
2. send it to me: vs at vs-dev.com 
3. send to me at least few end lines of file and/or a place where near character offset 139389.

**Comment by michelpereira** [comment]
Hi.

I run the command again and it gives me no more error.

Sorry.

**Comment by vsespb** [comment]
sure, np.
let me know if see this again.
