### ISSUE TITLE
sync strategy

### ISSUE THREAD

**Issue by cgfrosty** [vsespb/mt-aws-glacier#30]
Hi,

We are very happy with your script. We have just 1 question.

Is it possible to delete file in vault in the process of synchronization when this file was deleted in source folder? Our inventory become very large.

Or we should delete all files in vault sometimes and do new sync?

Thank you!

Alex

**Comment by vsespb** [comment]
Hello.
Currently `sync` syncs only new files. Syncing modified files and propagating deletions is a important missing feature.
(I've just added this to to list of important missing features in README)

Implementing this is probably highest priority now, so should be done soon (however I cannot tell when exactly).
I will leave this ticket open until this done.

**Comment by cgfrosty** [comment]
Thank you very much! We start waiting. :)

**Comment by bovnet** [comment]
+1 

-------Original Message-------

From: cgfrosty

Date: 21/03/2013 07:02:20

To: vsespb/mt-aws-glacier

Subject: Re: [mt-aws-glacier] sync strategy (#30)

Thank you very much! We start waiting. :)

**Comment by jondavidjohn** [comment]
:+1:

**Comment by Kitof** [comment]
+1 I need this ! Thanks ;)

**Comment by chrisgahlert** [comment]
:+1: as well. 

Please keep in mind that a point in time recovery would also be very nice.  I mean that when a file gets deleted locally it should not (immediately) be deleted at the remote end.

Anyway: Thanks for the awesome work so far!!

**Comment by vsespb** [comment]
`I mean that when a file gets deleted locally it should not (immediately) be deleted at the remote end.`
yes, this will be done some day too. (at least because Amazon Glacier has additional fee for early deletion)

`Please keep in mind that a point in time recovery would also be very nice.`
Planning this too, but lower priority

**Comment by vsespb** [comment]
Syncing modified files and propagating deletions done in 0.971beta. `sync` command behaviour documented. (see ChangeLog). 

Thus I am closing this issue. But I am opening two new:

> I mean that when a file gets deleted locally it should not (immediately) be deleted at the remote end.

#40 

> Please keep in mind that a point in time recovery would also be very nice.

#39

You can subscribe to these issues if you're waiting for such functionality.

**Comment by chrisgahlert** [comment]
Thanks & good work!!!
