### ISSUE TITLE
sync from network shares

### ISSUE THREAD

**Issue by morcant** [vsespb/mt-aws-glacier#31]
I have a NAS backup appliance that serves out a CIFS share. When attempting to run a sync with --dir from a path on this share, nothing is backed up. When I move those same files locally, the sync runs fine.

Example:
# Does not backup

./mtglacier sync --config=glacier.cfg --vault=test --dir=/mnt/backup/tmp --journal=journal.log

mv /mnt/backup/tmp /tmp/
# Works

./mtglacier sync --config=glacier.cfg --vault=test --dir=/tmp/tmp --journal=journal.log

Would like to be able to sync from CIFS shares.

**Comment by vsespb** [comment]
Hello. I've just tested with CIFS, it works for me.
Could you pls send to me
1. You OS type, distro and version
2. `cat /etc/mtab`
3. `ls -la` inside /mnt/backup/tmp and inside /mnt/backup
4. make sure `find .` inside /mnt/backup/tmp is working (i.e. list all files recursively)
5. make sure files inside /mnt/backup/tmp are readable  (i.e. try `md5sum *` it should finish without error)
6. copy console output of `mtglacier sync` when it does not sync.

**Comment by vsespb** [comment]
and perl version please: `perl -V`

**Comment by morcant** [comment]
# cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.10
DISTRIB_CODENAME=quantal
DISTRIB_DESCRIPTION="Ubuntu 12.10"

# uname -a

Linux mon01 3.5.0-17-generic #28-Ubuntu SMP Tue Oct 9 19:31:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

# perl -v

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
...

# cat /etc/mtab

/dev/sda1 / ext4 rw,errors=remount-ro 0 0
proc /proc proc rw,noexec,nosuid,nodev 0 0
sysfs /sys sysfs rw,noexec,nosuid,nodev 0 0
none /sys/fs/fuse/connections fusectl rw 0 0
none /sys/kernel/debug debugfs rw 0 0
none /sys/kernel/security securityfs rw 0 0
udev /dev devtmpfs rw,mode=0755 0 0
devpts /dev/pts devpts rw,noexec,nosuid,gid=5,mode=0620 0 0
tmpfs /run tmpfs rw,noexec,nosuid,size=10%,mode=0755 0 0
none /run/lock tmpfs rw,noexec,nosuid,nodev,size=5242880 0 0
none /run/shm tmpfs rw,nosuid,nodev 0 0
none /run/user tmpfs rw,noexec,nosuid,nodev,size=104857600,mode=0755 0 0
//CONSOLE01/Backup /mnt/backup cifs rw 0 0
//DB001/f$ /mnt/db001backup cifs rw 0 0

# ls -la /mnt/backup/tmp/

total 8
drwxr-xr-x 0 root root    0 Apr  4 16:56 .
drwxr-xr-x 2 root root 8192 Apr  4 21:00 ..
drwxr-xr-x 0 root root    0 Apr  4 17:01 Configs

# find /mnt/backup/tmp/

/mnt/backup/tmp/
/mnt/backup/tmp/Configs
/mnt/backup/tmp/Configs/ADHOSTFW01-sonicwall-NSA_3500-5_8_1_8-57o.exp
/mnt/backup/tmp/Configs/ADHOSTFW02-sonicwall-NSA_3500-5_8_1_8-57o.exp
/mnt/backup/tmp/Configs/ADHOSTSWITCH01.pcc
/mnt/backup/tmp/Configs/ADHOSTSWITCH02.pcc
/mnt/backup/tmp/Configs/Debug
/mnt/backup/tmp/Configs/Debug/Apache.NMS.ActiveMQ.dll
/mnt/backup/tmp/Configs/Debug/Apache.NMS.ActiveMQ.pdb
/mnt/backup/tmp/Configs/Debug/Apache.NMS.dll
/mnt/backup/tmp/Configs/Debug/Apache.NMS.pdb
/mnt/backup/tmp/Configs/Debug/ClaimService.exe
/mnt/backup/tmp/Configs/Debug/ClaimService.exe.config
/mnt/backup/tmp/Configs/Debug/ClaimService.pdb
/mnt/backup/tmp/Configs/Debug/ClaimService.vshost.exe
/mnt/backup/tmp/Configs/Debug/ClaimService.vshost.exe.config
/mnt/backup/tmp/Configs/Debug/ClaimService.vshost.exe.manifest
/mnt/backup/tmp/Configs/Debug/Newtonsoft.Json.dll
/mnt/backup/tmp/Configs/Debug/Newtonsoft.Json.xml
/mnt/backup/tmp/Configs/Debug/OopFactory.X12.dll
/mnt/backup/tmp/Configs/t
/mnt/backup/tmp/Configs/t2

# find /mnt/backup/tmp/ | xargs md5sum

md5sum: /mnt/backup/tmp/: Is a directory
md5sum: /mnt/backup/tmp/Configs: Is a directory
da09c08901d2e06dcf2e03b1826aee52  /mnt/backup/tmp/Configs/ADHOSTFW01-sonicwall-NSA_3500-5_8_1_8-57o.exp
ff42757df49ffb5441038e822463ade1  /mnt/backup/tmp/Configs/ADHOSTFW02-sonicwall-NSA_3500-5_8_1_8-57o.exp
a463c9b5a78f49c325bb8fe42645718a  /mnt/backup/tmp/Configs/ADHOSTSWITCH01.pcc
17f4edc290941921934f5ab335d03d84  /mnt/backup/tmp/Configs/ADHOSTSWITCH02.pcc
md5sum: /mnt/backup/tmp/Configs/Debug: Is a directory
f4b1d9a1e591adedfdf6b089f005a013  /mnt/backup/tmp/Configs/Debug/Apache.NMS.ActiveMQ.dll
0ed755f2eb16fbd2e8187b2bc824b28c  /mnt/backup/tmp/Configs/Debug/Apache.NMS.ActiveMQ.pdb
8582b2a598bd05b50cfd4e984e1f28de  /mnt/backup/tmp/Configs/Debug/Apache.NMS.dll
fb226d3fdb2b05484c80bb0e90811c66  /mnt/backup/tmp/Configs/Debug/Apache.NMS.pdb
44b87c0455b94fb05b1c9cad6fc5af17  /mnt/backup/tmp/Configs/Debug/ClaimService.exe
213108c4586bd23232161061c62a1947  /mnt/backup/tmp/Configs/Debug/ClaimService.exe.config
77439a245a032ed9f01bd9774107514a  /mnt/backup/tmp/Configs/Debug/ClaimService.pdb
a219fda38d52905ccf484f9f300b69b3  /mnt/backup/tmp/Configs/Debug/ClaimService.vshost.exe
213108c4586bd23232161061c62a1947  /mnt/backup/tmp/Configs/Debug/ClaimService.vshost.exe.config
a19a2658ba69030c6ac9d11fd7d7e3c1  /mnt/backup/tmp/Configs/Debug/ClaimService.vshost.exe.manifest
8611795b70cd1f321cb5cb5aad95ff7b  /mnt/backup/tmp/Configs/Debug/Newtonsoft.Json.dll
84a9baf16ca13f2b4dc2786114fed347  /mnt/backup/tmp/Configs/Debug/Newtonsoft.Json.xml
72fb30e343aa4bbddb5aa401c7d0b057  /mnt/backup/tmp/Configs/Debug/OopFactory.X12.dll
29e3fe14fa8b42ca34545cdaf3a40237  /mnt/backup/tmp/Configs/t
5e37766b1698e11eb369e284678549c1  /mnt/backup/tmp/Configs/t2

# /usr/src/mt-aws-glacier-master/mtglacier --config /usr/src/mt-aws-glacier-master/glacier.cfg --vault=test --dir=/mnt/backup/tmp --journal=/usr/src/mt-aws-glacier-master/journal.log sync

MT-AWS-Glacier, Copyright 2012-2013 Victor Efimov http://mt-aws.com/ Version 0.936beta

PID 3479 Started worker
PID 3480 Started worker
PID 3481 Started worker
PID 3482 Started worker
OK DONE

# mv /mnt/backup/tmp /tmp/

# /usr/src/mt-aws-glacier-master/mtglacier --config /usr/src/mt-aws-glacier-master/glacier.cfg --vault=test --dir=/tmp/tmp --journal=/usr/src/mt-aws-glacier-master/journal.log sync

MT-AWS-Glacier, Copyright 2012-2013 Victor Efimov http://mt-aws.com/ Version 0.936beta

PID 4488 Started worker
PID 4489 Started worker
PID 4490 Started worker
PID 4491 Started worker
Skip Configs/ADHOSTFW02-sonicwall-NSA_3500-5_8_1_8-57o.exp
Skip Configs/t2
Skip Configs/ADHOSTFW01-sonicwall-NSA_3500-5_8_1_8-57o.exp
Skip Configs/t
Skip Configs/ADHOSTSWITCH02.pcc
Skip Configs/ADHOSTSWITCH01.pcc
Skip Configs/Debug/ClaimService.pdb
Skip Configs/Debug/ClaimService.vshost.exe.manifest
Skip Configs/Debug/ClaimService.exe.config
Skip Configs/Debug/Apache.NMS.ActiveMQ.dll
Skip Configs/Debug/ClaimService.vshost.exe
Skip Configs/Debug/Newtonsoft.Json.dll
Skip Configs/Debug/Newtonsoft.Json.xml
Skip Configs/Debug/Apache.NMS.pdb
Skip Configs/Debug/ClaimService.vshost.exe.config
Skip Configs/Debug/Apache.NMS.ActiveMQ.pdb
Skip Configs/Debug/ClaimService.exe
Skip Configs/Debug/OopFactory.X12.dll
Skip Configs/Debug/Apache.NMS.dll
OK DONE

**Comment by morcant** [comment]
Ugh... so after unmounting and remounting the share it's working... no idea why it wasn't working before. Sorry to have wasted your time.

**Comment by vsespb** [comment]
thanks. expect fix on Sunday
 05.04.2013 21:42 ÐÏÌØÚÏ×ÁÔÅÌØ "morcant" notifications@github.com ÎÁÐÉÓÁÌ:

**Comment by vsespb** [comment]
ah. if it's working could you pls provide ls -la after remount?
05.04.2013 22:26 ÐÏÌØÚÏ×ÁÔÅÌØ "Victor Efimov" victor@vsespb.ru ÎÁÐÉÓÁÌ:

**Comment by morcant** [comment]
# ls -la /mnt/backup/tmp

total 8
drwxr-xr-x 2 root root 8192 Apr  5 11:51 .
drwxr-xr-x 2 root root 8192 Apr  5 11:14 ..
drwxr-xr-x 0 root root 8192 Apr  5 11:51 Configs

Looks like it's ignoring 0 length files, even if they are folders? 

fscache probably doesn't save directory size since its always the same and returns 0 after it's cached?

**Comment by vsespb** [comment]
```
drwxr-xr-x 0 root root 0 Apr 4 17:01 Configs
```

Number '0' to the right of permissions means number of hardlinks to a directory.
On normal (Unix/POSIX) filesystem it should be = 2 + NUMBER OF SUBDIRECTORIES (i.e. 2, minumum, not 0)

(Some) CIFS/CD-ROM filesystems are known to not follow this convention.

Both `find` tool and Perl module `File::Find` that mtglacier uses, use that hardlinks number to speedup directory traversal.
However both of them detect wrong number of hardlinks (0 or 1) and use normal traversal.

Also there are options for both to force 'normal' traversal and ignore number of hardlinks (with some explanations)

`find`: option `-noleaf` http://unixhelp.ed.ac.uk/CGI/man-cgi?find
`File::Find`: `$dont_use_nlink` http://search.cpan.org/perldoc?File%3A%3AFind

(I believe that means that sometimes autodetection cannot be done)

Also, `find` sometimes can issue warnings like this one:

```
WARNING: Hard link count is wrong for XXXX: this may be a bug in your filesystem driver. Automatically turning on find's -noleaf option. Earlier results may have failed to include directories that should have been searched.
```

In the output, that you provided, I see number of harlinks = 0, so CIFS should be detected correctly, and everything should work.
Also `find` works fine.

However there is no `ls -la` for `/mnt/backup/` thus I cannot tell if number of hardlinks for /mnt/backup/tmp is 0 or not.
If it was '2' that would explain everything (File::Find is definitely sensitive to number of hardlinks to first directory, and I am not sure about `find` tool)

I think I will release new version tomorrow, and add an option to force slow traversal (like -noleaf in `find`). I have no other ideas yet why this issue happened.

> Looks like it's ignoring 0 length files, even if they are folders? 

seems no, it traverse into with /proc on my system, which reports size=0

**Comment by vsespb** [comment]
Version  0.941 released. You'll need to put `leaf-optimization=0` into config file. I hope this will help avoid this bug in the future. Please let me know if this options helps for sure or does not help for sure.

**Comment by morcant** [comment]
Just wanted to let you know this does indeed resolve my problem.

**Comment by vsespb** [comment]
ok. thanks!
17.04.2013 2:59 ÐÏÌØÚÏ×ÁÔÅÌØ "morcant" notifications@github.com ÎÁÐÉÓÁÌ:

**Comment by hferentschik** [comment]
Same here, I had the same issue. Trying to back-up a CIFS mounted NAS and the backup would only find and sync the files in the top level directories. I tried to get _mt-aws-glacier_ to recurse with filter options and tried re-mounting the drive, nothing helped. 

    leaf-optimization=0

in the config filed resolved the issue.
