### ISSUE TITLE
CPAN install on Fedora 18

### ISSUE THREAD

**Issue by mstajd** [vsespb/mt-aws-glacier#41]
I've installed mt-aws-glacier from CPAN and I get error when running a query (and other commands) .    Previously I'd installed via git and it ran perfectly well, but I haven't tried this update yet.

$ mtglacier retrieve-inventory --config=config.txt --vault=test
String found where operator expected at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 37, near "message 'filter_error'"
    (Do you need to predeclare message?)
String found where operator expected at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 38, near "scope 'filters'"
    (Do you need to predeclare scope?)
Array found where operator expected at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 42, at end of line
    (Do you need to predeclare lists?)
String found where operator expected at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 88, near "message 'mutual'"
    (Do you need to predeclare message?)
String found where operator expected at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 89, near "message 'mandatory_with'"
    (Do you need to predeclare message?)
String found where operator expected at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 100, near "validate 'dir'"
    (Do you need to predeclare validate?)
syntax error at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 37, near "message 'filter_error'"
syntax error at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 42, near "lists @l"
Global symbol "$filter_error" requires explicit package name at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 45.
syntax error at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 45, near "} if"
syntax error at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 48, near "} elsif"
Global symbol "$F" requires explicit package name at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 49.
Global symbol "@l" requires explicit package name at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 54.
Global symbol "$F" requires explicit package name at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 54.
Global symbol "@l" requires explicit package name at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 56.
syntax error at /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm line 100, near "validate 'dir'"
/usr/local/share/perl5/App/MtAws/ConfigDefinition.pm has too many errors.
Compilation failed in require at /usr/local/share/perl5/App/MtAws.pm line 60.
BEGIN failed--compilation aborted at /usr/local/share/perl5/App/MtAws.pm line 60.
Compilation failed in require at /usr/local/bin/mtglacier line 5.
BEGIN failed--compilation aborted at /usr/local/bin/mtglacier line 5.

**Comment by vsespb** [comment]
Hello.

I need output of the following commands:
1. `ls -la /usr/local/bin/mtglacier`
2. `cat  /usr/local/bin/mtglacier`
3. `which perl`
4. `grep "VERSION " /usr/local/share/perl5/App/MtAws.pm`
5. A directory name where you previously manually installed mtglacier (from git)
6. `grep "VERSION " lib/App/MtAws.pm` inside that directory
7. `perl -V`
8. `perl -MModule::Build -e 'print Module::Build->VERSION'`
9. `perl -MCPAN -e 'print CPAN->VERSION'`
10. did you use `cpan` or alternatives: CPANPlus (`cpanp`), CPANMinus (`cpanm`)?

**Comment by vsespb** [comment]
also probably `md5sum /usr/local/share/perl5/App/MtAws/ConfigDefinition.pm`

**Comment by vsespb** [comment]
So, I did not receive feedback from you, but I have pretty strong theory on what happened.

This error message means that code from new version loaded `ConfigEngine.pm` from older versions `0.86` or `0.87`.
Also stacktrace shows that `mtglacier` script is from old version too.

I am not enterelly sure how this could happen, perhaps you manually installed old versions into system directories (/usr/*/) and/or had some file permissions issue.

To fix this manually remove older version, that you manually installed. Also make sure to remove `/usr/local/bin/mtglacier`

then reinstall the module from cpan:

```
$ cpan
reload index
force install App::MtAws
```

Also, I recently released `0.974`. This wersion will check all loaded modules at runtime and produce error message if module is from older version.
I think in you case it's only safe to use `0.974`\+ on production, only with this version you can be sure that files from different version are not mixed.

And I updated install instructions for Fedore/RHEL, but that is unrelated to this case.

pls feel free to reopen ticket is this does not help.
