### ISSUE TITLE
When uploading file content is "0" , error occured  "UNEXPECTED ERROR"

### ISSUE THREAD

**Issue by tgk1** [vsespb/mt-aws-glacier#42]
When uploading file content is "0" , error occured  "UNEXPECTED ERROR"

<pre>
UNEXPECTED ERROR (child ***):  at mt-aws-glacier/lib/App/MtAws/GlacierRequest.pm line 104
        App::MtAws::GlacierRequest::upload_part('App::MtAws::GlacierRequest=HASH(0x302ca98)', 'JG-1tB9qhBfv7LjzAB_t5Ww8gR7SQVJxtEXf78AJ0FZgUBTs-Jqw9_Zu_n5XY...', undef, 0, '5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9') called at mt-aws-glacier/lib/App/MtAws/ChildWorker.pm line 80
        App::MtAws::ChildWorker::process('App::MtAws::ChildWorker=HASH(0x290c188)') called at mt-aws-glacier/lib/App/MtAws/ForkEngine.pm line 108
        eval {...} called at mt-aws-glacier/lib/App/MtAws/ForkEngine.pm line 108
        App::MtAws::ForkEngine::start_children('App::MtAws::ForkEngine=HASH(0x2ebf1c0)') called at mt-aws-glacier/lib/App/MtAws/ForkEngine.pm line 58
        App::MtAws::ForkEngine::with_forks(1, 'HASH(0x2f2da48)', 'CODE(0x2f34d38)') called at mt-aws-glacier/lib/App/MtAws/SyncCommand.pm line 210
        App::MtAws::SyncCommand::run('HASH(0x2f2da48)', 'App::MtAws::Journal=HASH(0x2ce2228)') called at mt-aws-glacier/lib/App/MtAws.pm line 164
        App::MtAws::process() called at mt-aws-glacier/lib/App/MtAws.pm line 113
        eval {...} called at mt-aws-glacier/lib/App/MtAws.pm line 113
        App::MtAws::main() called at ./mtglacier line 4
</pre>

<pre>
diff --git a/lib/App/MtAws/LineProtocol.pm b/lib/App/MtAws/LineProtocol.pm
index 8bbdab5..f6baa76 100644
--- a/lib/App/MtAws/LineProtocol.pm
+++ b/lib/App/MtAws/LineProtocol.pm
@@ -72,7 +72,7 @@ sub get_data
                        return;
        }
        my $data = decode_data($data_e);
-   return ($pid, $action, $taskid, $data, $attachment ? \$attachment : ());
+ return ($pid, $action, $taskid, $data, defined($attachment) ? \$attachment : ());
 }
 
 sub send_data
</pre>

**Comment by vsespb** [comment]
Thanks! I can't believe I did not have testcase for this. Fixed in `0.975`
