### ISSUE TITLE
error while syncing with --delete-removed

### ISSUE THREAD

**Issue by kentnielsen** [vsespb/mt-aws-glacier#44]
Hi.

Great piece of software, it work good so far, except when trying to delete from vault with  "--delete-removed".  It gives an error below.  How could I debug further?
I says invalid vault, although sync works perfectly with the same command, just without "--delete-removed".

Error:
===REQUEST:
DELETE http://glacier.eu-west-1.amazonaws.com/-/vaults/helena/archives/***REMOVED***
Authorization: AWS4-HMAC-SHA256 Credential=**_REMOVED**_/20130915/eu-west-1/glacier/aws4_request, SignedHeaders=host;x-amz-date;x-amz-glacier-version, Signature=**_REMOVED**_
Host: glacier.eu-west-1.amazonaws.com
User-Agent: mt-aws-glacier/1.051 (http://mt-aws.com/) libwww-perl/6.04
X-Amz-Date: 20130915T082648Z
X-Amz-Glacier-Version: 2012-06-01

===RESPONSE:
HTTP/1.1 400 Bad Request
Date: Sun, 15 Sep 2013 08:27:26 GMT
Content-Length: 142
Content-Type: application/json
Client-Date: Sun, 15 Sep 2013 08:27:26 GMT
Client-Peer: 178.236.7.103:80
Client-Response-Num: 1
X-Amzn-RequestId: x-MLCr04NMP2khb9DcFzgfD5chucO40hpIQ1Dh7cnWk0-zA

{"code":"InvalidParameterValueException","message":"Invalid vault name: arn:aws:glacier:eu-west-1:149083434021:vaults/helena","type":"Client"}

ERROR (child 2838): Unexpected reply from remote server
Error:
===REQUEST:
DELETE http://glacier.eu-west-1.amazonaws.com/-/vaults/helena/archives/***REMOVED***
Authorization: AWS4-HMAC-SHA256 Credential=**_REMOVED**_/20130915/eu-west-1/glacier/aws4_request, SignedHeaders=host;x-amz-date;x-amz-glacier-version, Signature=**_REMOVED**_
Host: glacier.eu-west-1.amazonaws.com
User-Agent: mt-aws-glacier/1.051 (http://mt-aws.com/) libwww-perl/6.04
X-Amz-Date: 20130915T082648Z
X-Amz-Glacier-Version: 2012-06-01

===RESPONSE:
HTTP/1.1 400 Bad Request
Date: Sun, 15 Sep 2013 08:27:26 GMT
Content-Length: 142
Content-Type: application/json
Client-Date: Sun, 15 Sep 2013 08:27:26 GMT
Client-Peer: 178.236.7.103:80
Client-Response-Num: 1
X-Amzn-RequestId: DtvNiP8eGj0b74dYY0qCVCLgOi6dYURh0ulH7NEvXuOPkFA

{"code":"InvalidParameterValueException","message":"Invalid vault name: arn:aws:glacier:eu-west-1:149083434021:vaults/helena","type":"Client"}

Error:
===REQUEST:
DELETE http://glacier.eu-west-1.amazonaws.com/-/vaults/helena/archives/***REMOVED***
Authorization: AWS4-HMAC-SHA256 Credential=**_REMOVED**_/20130915/eu-west-1/glacier/aws4_request, SignedHeaders=host;x-amz-date;x-amz-glacier-version, Signature=**_REMOVED**_
Host: glacier.eu-west-1.amazonaws.com
User-Agent: mt-aws-glacier/1.051 (http://mt-aws.com/) libwww-perl/6.04
X-Amz-Date: 20130915T082648Z
X-Amz-Glacier-Version: 2012-06-01

===RESPONSE:
HTTP/1.1 400 Bad Request
Date: Sun, 15 Sep 2013 08:27:26 GMT
Content-Length: 142
Content-Type: application/json
Client-Date: Sun, 15 Sep 2013 08:27:27 GMT
Client-Peer: 178.236.7.103:80
Client-Response-Num: 1
X-Amzn-RequestId: 5vQE_1nc-kOjEsCE3GvIx-YUMTs1Iwaf-zgFdOo6ctImsA0

{"code":"InvalidParameterValueException","message":"Invalid vault name: arn:aws:glacier:eu-west-1:149083434021:vaults/helena","type":"Client"}

ERROR (child 2835): Unexpected reply from remote server
Error:
ERROR (child 2836): Unexpected reply from remote server
===REQUEST:
DELETE http://glacier.eu-west-1.amazonaws.com/-/vaults/helena/archives/l***REMOVED***
Authorization: AWS4-HMAC-SHA256 Credential=**_REMOVED**_/20130915/eu-west-1/glacier/aws4_request, SignedHeaders=host;x-amz-date;x-amz-glacier-version, Signature=**_REMOVED**_
Host: glacier.eu-west-1.amazonaws.com
User-Agent: mt-aws-glacier/1.051 (http://mt-aws.com/) libwww-perl/6.04
X-Amz-Date: 20130915T082648Z
X-Amz-Glacier-Version: 2012-06-01

===RESPONSE:
HTTP/1.1 400 Bad Request
Date: Sun, 15 Sep 2013 08:27:26 GMT
Content-Length: 142
Content-Type: application/json
Client-Date: Sun, 15 Sep 2013 08:27:27 GMT
Client-Peer: 178.236.7.103:80
Client-Response-Num: 1
X-Amzn-RequestId: 9b81WYeLeMcaFEA0FFNROsfHpbo0U92P27NF6INXpLc5Hyk

{"code":"InvalidParameterValueException","message":"Invalid vault name: arn:aws:glacier:eu-west-1:149083434021:vaults/helena","type":"Client"}

ERROR (child 2837): Unexpected reply from remote server
EXIT eof/error when communicate with child process

EXIT on SIGCHLD

**Comment by vsespb** [comment]
Hello.

`Invalid vault name` does not mean what it sounds like. It means vault name is ok. But this archive_id is located in different vault. ( proof: https://forums.aws.amazon.com/message.jspa?messageID=446187 )

So most likely you used same journal file with different vaults. If it's the case, it will be hard to understand which file belongs to which vault now. and I'd suggest either:

1) drop all your archives in all vaults and start from scratch
2) Use `retrieve-inventory`+`download-inventory` command to obtain "clean" journal files with actual list of archvies for each vault.

more info:

https://github.com/vsespb/mt-aws-glacier#how-to-maintain-a-relation-between-my-journal-files-and-my-vaults
https://github.com/vsespb/mt-aws-glacier#why-journal-does-not-contain-regionvault-information
https://github.com/vsespb/mt-aws-glacier#journal-concept

**Comment by vsespb** [comment]
also I created new ticket #45 - more sane handling of Amazon errors

**Comment by vsespb** [comment]
similar old issue #32

**Comment by vsespb** [comment]
Closing for now, let me know if you have questions or other concerns - I will reopen then.
