### ISSUE TITLE
Unexpected error on download-inventory

### ISSUE THREAD

**Issue by nconnor** [vsespb/mt-aws-glacier#48]
Running ./mtglacier download-inventory --config=glacier.cfg --vault=text --new-journal=text-journal.log I get the error

"UNEXPECTED ERROR (parent): malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "ArchiveId,ArchiveDes...") at /home/neal/mt-aws-glacier/lib/App/MtAws/Command/DownloadInventory.pm line 61."

using latest version of mt-glacier and JSON::XS

**Comment by vsespb** [comment]
Hello.
1. Could you pls send me full output of `mtglacier --version` (this will output all module versions - not only JSON::XS involved to JSON processing).
2. Your OS and version
3. Did you try once or several times? Subsequent tries produce same results?
4. appx. number of files you expect to see in the inventory?

**Comment by nconnor** [comment]
MT-AWS-Glacier, Copyright 2012-2013 Victor Efimov http://mt-aws.com/ Version 1.056

mt-aws-glacier version: 1.056
Perl Version: 5.014002
AutoLoader      5.71    /usr/share/perl/5.14/AutoLoader.pm
Carp    1.20    /usr/share/perl/5.14/Carp.pm
Carp::Heavy     undef   /usr/share/perl/5.14/Carp/Heavy.pm
Class::Struct   0.63    /usr/share/perl/5.14/Class/Struct.pm
Config  undef   /usr/lib/perl/5.14/Config.pm
Cwd     3.36    /usr/lib/perl/5.14/Cwd.pm
Digest::SHA     5.71    /usr/lib/perl5/Digest/SHA.pm
Digest::base    1.16    /usr/share/perl/5.14/Digest/base.pm
DynaLoader      1.13    /usr/lib/perl/5.14/DynaLoader.pm
Encode  2.42_01 /usr/lib/perl/5.14/Encode.pm
Encode::Alias   2.13    /usr/lib/perl/5.14/Encode/Alias.pm
Encode::Config  2.05    /usr/lib/perl/5.14/Encode/Config.pm
Encode::Encoding        2.05    /usr/lib/perl/5.14/Encode/Encoding.pm
Errno   1.13    /usr/lib/perl/5.14/Errno.pm
Exporter        5.64_03 /usr/share/perl/5.14/Exporter.pm
Exporter::Heavy 5.64_03 /usr/share/perl/5.14/Exporter/Heavy.pm
Fcntl   1.11    /usr/lib/perl/5.14/Fcntl.pm
File::Basename  2.82    /usr/share/perl/5.14/File/Basename.pm
File::Find      1.19    /usr/share/perl/5.14/File/Find.pm
File::Path      2.08_01 /usr/share/perl/5.14/File/Path.pm
File::Spec      3.33    /usr/lib/perl/5.14/File/Spec.pm
File::Spec::Unix        3.33    /usr/lib/perl/5.14/File/Spec/Unix.pm
File::Temp      0.22    /usr/share/perl/5.14/File/Temp.pm
File::stat      1.05    /usr/share/perl/5.14/File/stat.pm
FindBin 1.50    /usr/share/perl/5.14/FindBin.pm
Getopt::Long    2.38    /usr/share/perl/5.14/Getopt/Long.pm
HTTP::Date      6.02    /usr/share/perl5/HTTP/Date.pm
HTTP::Headers   6.00    /usr/share/perl5/HTTP/Headers.pm
HTTP::Message   6.03    /usr/share/perl5/HTTP/Message.pm
HTTP::Request   6.00    /usr/share/perl5/HTTP/Request.pm
HTTP::Response  6.03    /usr/share/perl5/HTTP/Response.pm
HTTP::Status    6.03    /usr/share/perl5/HTTP/Status.pm
I18N::Langinfo  0.08    /usr/lib/perl/5.14/I18N/Langinfo.pm
IO      1.25_04 /usr/lib/perl/5.14/IO.pm
IO::Handle      1.31    /usr/lib/perl/5.14/IO/Handle.pm
IO::Pipe        1.14    /usr/lib/perl/5.14/IO/Pipe.pm
IO::Seekable    1.1     /usr/lib/perl/5.14/IO/Seekable.pm
IO::Select      1.20    /usr/lib/perl/5.14/IO/Select.pm
JSON::XS        3.01    /usr/local/lib/perl/5.14.2/JSON/XS.pm
LWP     6.05    /usr/local/share/perl/5.14.2/LWP.pm
LWP::MemberMixin        undef   /usr/local/share/perl/5.14.2/LWP/MemberMixin.pm
LWP::Protocol   6.00    /usr/local/share/perl/5.14.2/LWP/Protocol.pm
LWP::UserAgent  6.05    /usr/local/share/perl/5.14.2/LWP/UserAgent.pm
List::Util      1.23    /usr/lib/perl/5.14/List/Util.pm
MIME::Base64    3.13    /usr/lib/perl/5.14/MIME/Base64.pm
POSIX   1.24    /usr/lib/perl/5.14/POSIX.pm
PerlIO::encoding        0.14    /usr/lib/perl/5.14/PerlIO/encoding.pm
Scalar::Util    1.23    /usr/lib/perl/5.14/Scalar/Util.pm
SelectSaver     1.02    /usr/share/perl/5.14/SelectSaver.pm
Storable        2.27    /usr/lib/perl/5.14/Storable.pm
Symbol  1.07    /usr/share/perl/5.14/Symbol.pm
Tie::Hash       1.04    /usr/share/perl/5.14/Tie/Hash.pm
Time::Local     1.2000  /usr/share/perl/5.14/Time/Local.pm
Time::localtime 1.02    /usr/share/perl/5.14/Time/localtime.pm
Time::tm        1.00    /usr/share/perl/5.14/Time/tm.pm
Types::Serialiser       0.03    /usr/local/share/perl/5.14.2/Types/Serialiser.pm
URI     1.60    /usr/share/perl5/URI.pm
URI::Escape     3.31    /usr/share/perl5/URI/Escape.pm
XSLoader        0.13    /usr/share/perl/5.14/XSLoader.pm
attributes      0.14    /usr/lib/perl/5.14/attributes.pm
base    2.16    /usr/share/perl/5.14/base.pm
bytes   1.04    /usr/share/perl/5.14/bytes.pm
common::sense   3.6     /usr/share/perl5/common/sense.pm
constant        1.21    /usr/share/perl/5.14/constant.pm
integer 1.00    /usr/share/perl/5.14/integer.pm
lib     0.63    /usr/lib/perl/5.14/lib.pm
overload        1.13    /usr/share/perl/5.14/overload.pm
strict  1.04    /usr/share/perl/5.14/strict.pm
utf8    1.09    /usr/share/perl/5.14/utf8.pm
vars    1.02    /usr/share/perl/5.14/vars.pm
warnings        1.12    /usr/share/perl/5.14/warnings.pm
warnings::register      1.02    /usr/share/perl/5.14/warnings/register.pm
OK DONE

**Comment by nconnor** [comment]
Ubuntu Raring

Several tries reproduce results

Expect to see a large number of small-iah files - like 2200.

Thanks!

**Comment by vsespb** [comment]
Did you tried to perform retrieve inventory operation using _different_ software last 24 hours?
this string `before "ArchiveId,ArchiveDes..."` looks like inventory is in CSV format.

`mtglacier` always request JSON format, but if previously someone retrieved inventory is CSV, it will download CSV, and thus crash (that looks like a bug).

**Comment by nconnor** [comment]
Yes, I did! that would be it. Thanks!

**Comment by vsespb** [comment]
so, there are two bugs:
1. that one that you just find. it will download "foreign" inventory, possible in CSV.
2. unfortunately there is another one - if there are several inventory retrieval requests - it will download _oldest_ one, not newest one.

so, workaround for you now would be:
- wait when old CSV inventory request expired (i.e. 24+4 hours after CSV inventory requested).
- try to download inventory again via `mtglacier` (that step should be performed before new JSON inventory expired)

I'll keep this ticket open and will close it when fix both bugs. I don't think it would happen soon. Maybe week or two.

**Comment by vsespb** [comment]
both issues fixed in `1.103`, details are in changelog. closing this.
