### ISSUE TITLE
Archiving strategy

### ISSUE THREAD

**Issue by tofagerl** [vsespb/mt-aws-glacier#49]
This is an edge case, but probably a common one due to Glaciers pricing policy. 
I am using mt-aws-glacier to backup my Aperture archives, which is full of big images and tons of incredibly small metainformation files. Obviously I can use existing archiving tools to get everything to fit into a set of files with any filesize, but this is limiting since I am backing up from the working directory every few weeks - in other words, I would have to regenerate new archive files every time I want to sync to glacier. 

Would it be possible to include a pre-archiving functionality in mt-aws-glacier so that all files under XX bytes are zipped together to YY number of XX byte sized archives. With md5 or something similar, which I assume is already used, I would have to upload the archives which have been changed every time I sync, yet the amount of files synced would be considerably smaller.

I may have a go at editing this tomorrow. It's 10.40pm here and I'm not explaining very well...

**Comment by vsespb** [comment]
Hello.
What about:
1. upload only big images via mt-aws-glacier (using file filtering by name https://github.com/vsespb/mt-aws-glacier#file-selection-options )
2. compressing/archiving other small files using other tools (like .zip, rar, DAR (incremental), duplicity (incremental) ) into separate location (and then uploading it using mtglacier too)

OR

archive all you files using other tools, which support incremental backup, then upload its output via mtglacier (if backups are incremental, you'll have to upload increments, most likely)

**Comment by tofagerl** [comment]
That first one is a very good suggestion indeed. I'm going to write a small scriptlet to do just that, and I'll post it here. I might possibly have to rename/move files, but with cron I can have the backups run at night so that the files will have their proper names by the time I actually use the files at daytime.

Thanks!

**Comment by vsespb** [comment]
ok, cool, if you post it here others might reuse it some day.

**Comment by tofagerl** [comment]
I ended up going with this: 
http://gradha.github.io/dar-differential-backup-mini-howto/

I simplified the dar syntax by something like 90 %, but otherwise it works perfectly.

**Comment by vsespb** [comment]
ok, yeah I use DAR too, and I also had to write wrapper to simplify syntax
