### ISSUE TITLE
crashing out

### ISSUE THREAD

**Issue by bovnet** [vsespb/mt-aws-glacier#5]
Keeps crashing after a while of use with PARENT EXIT. how can i help u debug ?

With low bandwidth and a large backup is there any mechanism to detect already running if starting from a cron job ?

Also if not contradictory is there any option to periodically mirror local deletions to the vault ?

**Comment by vsespb** [comment]
> Keeps crashing after a while of use with PARENT EXIT. how can i help u debug ?

need more information - at least- how many files (count and size), how much time left before crash, what options used, copy of screen before crash, how much memory do you have

> With low bandwidth and a large backup is there any mechanism to detect already running if starting from a cron job ?

use linux 'flock' command

> Also if not contradictory is there any option to periodically mirror local deletions to the vault ?

coming soon.

**Comment by bovnet** [comment]
it an old box dedicated to backup only 256mb ram 512mb swap (plenty free) hooked up to my storage cluster. connected via fuse mount. trying to backup approx 3tb, 19k directories, 219k files 99% < 2gb, a handful 180gb but havent got to them yet. ./mtglacier.pl sync --config=glacier.cfg --from-dir /mnt/mfs --to-vault=bovsvault --journal=journal.log --concurrency=3 --partsize=8 same with no partsize specified. 

PID 14720 Finished /mnt/mfs/symf.tar.gz hash [3aad4ce4af3c4e118f5710679dd2cc6c6e483a70ce9bfb5da7020e18e28484ca] archive_id [0ynOur7WhSyTj7SY6ZzCxpeXntoCjo9xdxazcH7lBXbeeCOvAYOq8YN2KtP5E_6Bel-9dNoEKRBXJ88QOUvSl4KkdOQyfBGK_jneH2wrr3QOmcuawI4WSGsekjIo7tALfnyhqwSu7w]
PID 14721 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [0]
PID 14722 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [8388608]
PID 14720 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [16777216]
PID 14721 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [25165824]
PID 14722 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [33554432]
PID 14720 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [41943040]
PID 14721 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [50331648]
PID 14722 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [58720256]
PID 14720 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [67108864]
PID 14721 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [75497472]
PID 14722 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [83886080]
PID 14720 Uploaded part for /mnt/mfs/netbook/d/pagefile.sys at offset [92274688]
PARENT Exit

restarting will continue then fail on a later file, runs a few hours.

**Comment by vsespb** [comment]
ok, interesting. I'll try to investigate or hack a version with more verbose debug output. meanwhile could you please check /var/log/messages to make sure mtglacier was not killed my kernel due to memory issue (maybe memory leak in mtglacier etc). thanks.

**Comment by bovnet** [comment]
Oct 13 06:53:17 metabackup kernel: [144287.943397] Out of memory: Kill process 14716 (mtglacier.pl) score 333 or sacrifice child
Oct 13 06:53:17 metabackup kernel: [144287.956895] Killed process 14720 (mtglacier.pl) total-vm:107608kB, anon-rss:27056kB, file-rss:64kB

Moved on from iso size files to smaller ones and has run ok the rest of the day

**Comment by vsespb** [comment]
hm. memory usage should ~ (concurrency+1) \* partsize.

Maybe it's a bug and there is a memory leak - I'll try to reproduce, but I cannot try huge data sets due to high cost, so I will fake HTTP requests or hack glacier server emulator (but this will take time)
meanwhile could you just check 'top' - is memory usage constantly grows while uploading?

Another possible reason - high memory usage from the beginning due to large number of files - in this case 'top' will show huge memory usage right after script start - could you please check and tell me the number.

**Comment by bovnet** [comment]
After the 4-5 crashes and restarts it continues > 24 hrs without a crash. Yes it does look like the free ram is being eaten up with swap almost untouched.

**Comment by vsespb** [comment]
ok, i'll try to fake HTTP requests and reproduce long run process with large number of files, will check for memory issues.

**Comment by vsespb** [comment]
So I tested it with 2,000,000 files.
Average memory usage was 1.6kbytes/file, which is big but comparable with normal perl hash/array memory usage.

All that memory was allocated in the beginning, and then it did not grow.

So I think in your case it runs out of memory.

I'll try to optimize memory usage in the future (but I am not sure when).
Meanwhile I'll release a workaround soon (an option which will limit number of files to sync at once).

**Comment by bovnet** [comment]
Thanks

**Comment by vsespb** [comment]
Done. I added option --max-number-of-files for sync command + made some memory optimizations. (but btw still whole Journal file is read into memory). I expect it should work fine now in your configuration.
Watch for other memory optimizations in "Changes".
