### ISSUE TITLE
--filter and --exclude not working?

### ISSUE THREAD

**Issue by hotfloppy** [vsespb/mt-aws-glacier#52]
Hi, thanks for the great script. But I got some difficulties with --filter and --exclude. When mtglacier sync run, it said the excluded directory is skipped, but still uploading those directory and their subdirectories/files.

Operating System: FreeBSD 8.2

Here is all command that I tried:
mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --exclude 'cache/' --vault nginx-backup --journal nginx-backup.log --concurency 3

mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --exclude 'cache/**' --vault nginx-backup --journal nginx-backup.log --concurency 3

mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --exclude '/usr/local/etc/nginx/cache/' --vault nginx-backup --journal nginx-backup.log --concurency 3

mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --exclude '/usr/local/etc/nginx/cache/**' --vault nginx-backup --journal nginx-backup.log --concurency 3

mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --filter '-/usr/local/etc/nginx/cache/' --vault nginx-backup --journal nginx-backup.log --concurency 3

mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --filter '-/usr/local/etc/nginx/cache/**' --vault nginx-backup --journal nginx-backup.log --concurency 3

mtglacier sync --config ~/.glacier.cfg --dir /usr/local/etc/nginx --filter '-cache/' --vault nginx-backup --journal nginx-backup.log --concurency 3

**Comment by vsespb** [comment]
the first command you posted seem to work:

```
$ pwd
/tmp/test2/nginx


$ ls -laR
.:
total 252
drwxrwxr-x  3 vse  vse    4096 Nov 28 14:12 .
drwxrwxrwt 75 root root 245760 Nov 28 14:13 ..
drwxrwxr-x  3 vse  vse    4096 Nov 28 14:12 nginx

./nginx:
total 16
drwxrwxr-x 3 vse vse 4096 Nov 28 14:12 .
drwxrwxr-x 3 vse vse 4096 Nov 28 14:12 ..
drwxrwxr-x 2 vse vse 4096 Nov 28 14:13 cache
-rw-rw-r-- 1 vse vse    2 Nov 28 14:13 file

./nginx/cache:
total 12
drwxrwxr-x 2 vse vse 4096 Nov 28 14:13 .
drwxrwxr-x 3 vse vse 4096 Nov 28 14:12 ..
-rw-rw-r-- 1 vse vse    2 Nov 28 14:13 cachefile

mtglacier sync --config /tmp/glacier.cfg --dir /tmp/test2/nginx --exclude 'cache/' --vault nginx-backup --journal /tmp/nginx-backup.log --concurrency 3 --dry-run

$ mtglacier sync --config /tmp/glacier.cfg --dir /tmp/test2/nginx --exclude 'cache/' --vault nginx-backup --journal /tmp/nginx-backup.log --concurrency 3 --dry-run
MT-AWS-Glacier, Copyright 2012-2013 Victor Efimov http://mt-aws.com/ Version 1.058

Will UPLOAD /tmp/test2/nginx/file
OK DONE
```

note that this

```
sync --config /tmp/glacier.cfg --dir /tmp/test2/nginx --exclude '/cache/' --vault nginx-backup --journal /tmp/nginx-backup.log --concurrency 3 --dry-run
```

is more correct - i.e. "/cache/" instead of "cache/"
you have typo in `--concurrency 3`, maybe you have other typos ? maybe there were error messages?

**Comment by hotfloppy** [comment]
Wah, 1 more thing to respect, quick response :+1: 

Ops, yeah, got typo in my post, but my command is correct because there is no error produced. And actually I've put everything inside config file, just show them in full here for feedback purpose.

```
key=#blank#
secret=#blank#
region=ap-northeast-1
dir=/usr/local/etc/nginx
journal=nginx-backup.log
vault=nginx-backup
concurrency=5
```

I run the command like this:

```
mtglacier --config ~/.nginx-backup.conf --exclude 'cache/'
```

I just tried with '/cache/' and 'cache/', yes, both seems to work. I wonder why it's not working before. Btw, thanks so much :)

May I ask in here another thing (or should I create another topic?) ?
I tried editing some files and re-sync again, but seems like the mtglacier just syncing a new files only. Modified files are ignored. Is this normal?

**Comment by vsespb** [comment]
> Modified files are ignored. Is this normal?

yes, unless you use `--replace-modified` see here https://github.com/vsespb/mt-aws-glacier#sync

**Comment by vsespb** [comment]
> I just tried with '/cache/' and 'cache/', yes, both seems to work

`cache/` will exclude any directory named "cache" inside nginx. but `/cache/` will exclude only `nginx/cache`

**Comment by hotfloppy** [comment]
I see. Okay, thanks so much :)

:+1: :+1: :+1: :+1:
