### ISSUE TITLE
Using mt-aws-glacier to remove files from a vault?

### ISSUE THREAD

**Issue by philmarsay** [vsespb/mt-aws-glacier#53]
Apologies if this is not the best place for this but I couldn't see any other way to contact you.

I have a scenario where I have uploaded a number of archived backups to numerous vaults in amazon.

E.g. I have a vault for November 2013.

Is there a way/command within mt-aws-glacier to delete only selected files within a vault. E.g. I want to delete all items in the November 2013 vault that were created before the 16th November 2013?

I could not see any delete commands within the documentation other than for deleting the entire vault?

Is this possible at the moment, and if not do you know any other way in which I could achieve this?

many thanks!

Phil

**Comment by vsespb** [comment]
Hi. there is no filtering by upload time, but:
1. You can use `purge-vault` with file selection options https://github.com/vsespb/mt-aws-glacier#file-selection-options
   to filter what you wan't to delete by _filename_ and _filepath_ (not by time)
2. If you have all your files on local disk, you can delete unneeded localy and use `--delete-removed` option.
3. If you are familar with scripting/programming, you can extract from journal file only old files manually (i.e. filter journal by 2nd field - it's upload time
   in unix epoch format. fields separated by tabs). and then use this new journal with `purge-vault`

**Comment by philmarsay** [comment]
Thank you for the speedy reply!

Option 1 sounds promising – is there a way to see the filepaths in the vault? We upload folders with a timestamp on the end so if we could see the folder/paths in the vault then this would work.

Thanks again,
Phil

**Comment by vsespb** [comment]
>  is there a way to see the filepaths in the vault? 

`check-local-hash` will print it, but it's slow.

you can just view the journal file - filenames is in the last field.

also, it's highly recommended to use `--dry-run` first when deleting from vault and when testing file selection options. this will print filenames too.

actually you can `purge-vault` without file selection options, but with `--dry-run` - this will print all filenames as well

**Comment by philmarsay** [comment]
Excellent! I will give this a go – thank you – this is so helpful ☺

Regards,

Phil

**Comment by vsespb** [comment]
ok, I close the ticket then, let me know if you have other questions - I will reopen, or you can file new ticket. Currently Github issues is the only public interface to ask questions.
