### ISSUE TITLE
Cannot assign "dir" in config file where directory has spaces

### ISSUE THREAD

**Issue by ihartley-zz** [vsespb/mt-aws-glacier#60]
Get --dir not a directory error.  I'm guessing it interprets the space as the end of one argument - i.e. args > 1??  Tried single, double quotes and \ escape without success.  Eventually did a symlink which is fine; just thought I'd let you know.  Thanks.

**Comment by vsespb** [comment]
works fine for me:

```
region=us-east-1
protocol=http
dir=TEST/TEST2G/my files
```

could you print that part of your config here? also, is this cygwin?

**Comment by vsespb** [comment]
also works in command line:
`mtglacier --config glacier.cfg upload-file  --dir "TEST/TEST2G/my files"`

**Comment by ihartley-zz** [comment]
User error!!!!  Sorry.  I honestly don't know why I couldn't get it to work, but must have been a typo.  Sometimes you look and look but can't see what's wrong.
