### ISSUE TITLE
Can I delete *any* archive with mt-aws-glacier??

### ISSUE THREAD

**Issue by ihartley-zz** [vsespb/mt-aws-glacier#61]
Hi,

I have some old archives, possibly created with Cloudberry or Fastglacier.  Can i retrieve the journals and then delete them with this software?? (obviously the metadata will be different for restoring, but for delete?!).  Thanks

**Comment by vsespb** [comment]
yes you can with `purge-vault`

**Comment by vsespb** [comment]
so, seems you were able to do this (as per comment in another ticket # 55), so closing it.

**Comment by ihartley-zz** [comment]
Yes - works perfectly.  Thanks.

On Saturday, 14 December 2013, 22:28, Victor Efimov notifications@github.com wrote:

Closed #61.
