### ISSUE TITLE
Unable to run code using #!/usr/bin/perl

### ISSUE THREAD

**Issue by lembark** [vsespb/mt-aws-glacier#64]
./mt-aws-glacier/bin/mtglacier uses "#!/usr/bin/perl".

Catch is that I use an up-to-date copy in /opt/bin. Net result: The released code will never run here -- or on any system using perlbrew to maintain local, up-to-date perl executables.

Simple fix: 

```
#!/bin/env perl
```

which then uses the appropriate perl to execute the code (e.g., the one invoked to perform the install via "perl -MCPAN -E shell".

Given the Truly Ancient and Unusable order of /usr/bin/perl's
standard on distro's these days, most of the people I know use
perlbrew or roll their own into /usr/local or /opt.

**Comment by vsespb** [comment]
Hello. Thank you for report, but it's not a bug.

from docs:

```
After that you can execute mtglacier script (found in root of repository) from any directory
```

you need `mtglacier` in the _root_ of directory, it uses `/usr/bin/env perl` shebang.

`mtglacier` inside `bin/` is different. it's for CPAN install and tools based on it. Some CPAN tools don't like `/usr/bin/env` also they do replace `/usr/bin/perl` with real perl path (including perlbrew paths etc).
