### ISSUE TITLE
Choose which files to restore?

### ISSUE THREAD

**Issue by scallviz** [vsespb/mt-aws-glacier#65]
Hello, I've googled and did not find the answer so I'm sorry if this is redundant question.

I'm evaluating mtglacier for vaulting of files that no longer need to be online.  (IE sync a folder to glacier, make a local copy to HDD, and then delete it) .

This seems to work, however the restore process seems to attempt to restore an entire archive (or max # of files).

Is there currently a CLI option to retrieve one (or more) individual files by name?  If not, may I request it be added?

Thanks

**Comment by vsespb** [comment]
Hello. Yes, there is filtering by file/directory name: https://github.com/vsespb/mt-aws-glacier#file-selection-options
