### ISSUE TITLE
PID 5768 HTTP 500 This might be normal. Will retry 

### ISSUE THREAD

**Issue by degging** [vsespb/mt-aws-glacier#7]
I am getting this error when using your script. Is this due to IAM setting?

PID 5768 HTTP 500 This might be normal. Will retry

Thanks,
Degging

**Comment by vsespb** [comment]
Hello.
It's normal if retry is success in the end. Can happen when uploading large files.

See there https://github.com/vsespb/mt-aws-glacier/issues/4#issuecomment-9554585
https://forums.aws.amazon.com/thread.jspa?messageID=390950

Amazon explains that Glacier sometimes returns HTTP 500 and it's OK.
