### ISSUE TITLE
List Vaults (GET vaults)

### ISSUE THREAD

**Issue by ghost** [vsespb/mt-aws-glacier#70]
Does mt-aws-glacier support this operation? It would be nice to know how big the actual archive was at the last inventory. Documentation on AWS webpage http://docs.aws.amazon.com/amazonglacier/latest/dev/api-vaults-get.html

**Comment by vsespb** [comment]
Hello. No it does not support it (yet).

So, you want output to the screen listing of vault names + their sizes? (+ total size)

What about calculation of total size of files in Journal? (that will work only for vaults that you actually use, i.e. those which you have journal for)

**Comment by ghost** [comment]
I have about 100 GB of data to be uploaded to Glacier. The only way to monitor the progress of the upload (at least the way I am aware of) is to log into AWS console every morning and check the vault status. This is not very practical.

It would be nice to have the possibility to check how much data was already stored. Listing the vaults is one option. It would give a rough estimate of the amount of data stored. However, it is better than nothing ;) The other option that you propose, that is, journal-based method, would be very accurate, but could be harder to implement with all those created and deleted archives.

**Comment by vsespb** [comment]
Ok, get it, I understand your case now, thank you!

I will leave this ticket open as enhancement request, some day I'll implement something of it.

(not going to happen soon, I fix bugs fast, but new features are in low priority, thus we have no open bugs and a number of open feature request. I hope this leads to overall application reliability)

btw, I have same problem when use `mtglacier` - have no idea how many files uploaded already. In this case I add to current command `--dry-run` option - it at least print list of files to be uploaded (without sizes), so at least I understand what is in queue.

**Comment by kforner** [comment]
Some vault usage reporting would be very useful. The utimate one would be the actual one, not the one based on journals. 
I'll probably have to use another tool for that purpose in the meantime, such as 
glacier-cmd describevault

**Comment by kforner** [comment]
Hello,
I could not get glacier-cmd to work.
I could try to implement in mtglacier if you agree. I think it is quite isolated from other features. If you give me some advices to get started it should be ok. 
Otherwise I'll just write a simple script to access the web service.

**Comment by vsespb** [comment]
Hello. So you need for a given vault get number of archives and total size? (i.e. not list all vaults but get data for one specified). And yo'll be parsing it with script? What format? JSON/simple like CSV ? or Human readable (not for parsing)?

**Comment by kforner** [comment]
In fact, ideally I'd like the list of vaults and their sizes and nb of files (I think that is the output of the ListVaults service).
For the output, any easily parsable format could do, e.g. tsv (tab separated) which is both, or markdown.
My use case is to output each week/month by mail an overview of the company glacier usage.

**Comment by vsespb** [comment]
Ok, I'll try to implement it by end of July. In fact need to implement it with pagination, Amazon claims to return `the List Vaults operation returns up to 1,000 items` but in fact it means nothing, it really can return 1 vault (it's only guaranteed that it's less than 1000).

**Comment by kforner** [comment]
It would be quite nice if you could. 

Concerning the list vaults, maybe it is simpler to perform n describeVaults (one for each vault) than to use   List Vaults in that case.

**Comment by vsespb** [comment]
so both are ok for you - you could use describeVault as well (i.e. you already have vault names)?

**Comment by kforner** [comment]
yes sure.
But just to understand, currently you have no easy mean to just retrieve the list of vault names ?!

**Comment by vsespb** [comment]
I'll probably implement that what would be easier, have no much time right now. But ListVault looks a bit more complex than DescribeVault. I'll try ListVault of course (as this ticket is about ListVault anyway)

**Comment by vsespb** [comment]
UPD: implemeted ListVaults https://github.com/vsespb/mt-aws-glacier/pull/88 (merged into `development` branch) - will do a release this week.

**Comment by vsespb** [comment]
`list-vaults` command implemented in `1.120` - see the docs. thus closing.
