### ISSUE TITLE
Wrong file was requested

### ISSUE THREAD

**Issue by jtslear** [vsespb/mt-aws-glacier#73]
So thus far, this tool has been fantastic.  I'm running through some testing and I'm at the point where I've sent a retrieve operation, and then proceeded to download the file.  However the wrong file ended up being downloaded...

Do you know of a good way to troubleshoot this?  My journal file had 120 entries in there, and I formatted the filter command to choose one specific file.  This morning I go to download the file, and it was definitely not what I wanted...  Here's the two commands that had been used for this scenario:

```
mtglacier restore --config glacier.cfg --include 'it1-virt_Archive(1)_2013_06_19_10_30_13_708D.TIB' --dir restore --max-number-of-files 1 --journal journal/monthly-01-07-2013 --vault monthly-01-07-2013

mtglacier restore-completed --config glacier.cfg --dir restore --journal journal/monthly-01-07-2013 --vault monthly-01-07-2013
```

I did not get the file I expected.  Looking into the journal file , there's a long hash for both a CREATED and RETRIEVE_JOB that match, but was not the desired file.

So then I ran the exact same command again hoping for a fluke, but this time, it chose a different file to restore, again, not the file I'm looking for.  I then proceeded to try what I could with a combination of --filter and --include but at this point, not successful.  None of the below worked as expected:

```
--include 'it1-virt_Archive(1)_2013_06_19_10_30_13_708D.TIB'
--filter +it1-virt_Archive\(1\)_2013_06_19_10_30_13_708D.TIB
--filter +708D.TIB
--filter +708D\.TIB
--filter +*708D.TIB
```

So then I separated the journal file with ONLY the file I wanted, and of course as expected that is working. 

I feel I don't understand how the file selection process works.

**Comment by vsespb** [comment]
Hi. in the docs there is:

`How rules are processed`
`If no rules matched - file is included (default rule is INCLUDE rule).`
`--filter '+*.jpeg'` File `file.txt` is INCLUDED, as it does not match any rules`

so with `max-number-of-files=1` it will retrieve first/random file unrelated to rules specified.

so you need add last rule `-` like in this example:

`mtglacier ... --filter '+data/ -'` - Last pattern is empty string (followed by '-')

also, use `--dry-run` when testing filtering - it will print what it will do without doing that.

**Comment by jtslear** [comment]
Word, thank you sir.  I had glossed over that detail...
