### ISSUE TITLE
Vault size is less than the size of all uploaded archives

### ISSUE THREAD

**Issue by kolyuchiy** [vsespb/mt-aws-glacier#79]
I successfully uploaded 15 files to my vault. Their total size in kbytes according to du was 19756032. But Glacier console shows that my vault's size is only 18.84 GiB. Is this normal or should worry about this?

**Comment by vsespb** [comment]
**if** `du` thinks that I kbyte is 1024 bytes, **and** Amazon Console thinks that 1 GiB is `1024*1024*1024` bytes, then it's correct.

`19756032*1024=20230176768 bytes.`
`20230176768/(1024*1024*1024)=18.8408`

and yes, 1 GiB _must_ be `1024*1024*1024` .
and 1 kbyte is _usually_ 1024 bytes.

**Comment by kolyuchiy** [comment]
Wow, that was really stupid of me! I know about 1024 and stuff, but strangely my previous calculations showed different results. Sorry.
