### ISSUE TITLE
Uploading files with duplicate treehash

### ISSUE THREAD

**Issue by ihartley-zz** [vsespb/mt-aws-glacier#84]
Hi, Using v1.115.  I thought if the treehash was the same (even if different name/dir) it would bypass the file?!?  Am using the command:

mtglacier sync --config ./config/camcorder.cfg --new --replace-modified --detect treehash

What am I doing wrong??  Right now it is uploading files that already have a duplicate treehash in the journal file.  Thanks, Ian

**Comment by vsespb** [comment]
hello.

> even if different name/dir

no, for one file only.

```
--replace-modified

Uploads modified files (i.e. which exist in local filesystem and in Amazon Glacier). After file gets successfully uploaded, previous version of file is deleted. Logic of detection of modified files controlled by --detect option.

treehash - calculates TreeHash checksum for file and compares with one in Journal. If checksum does not match - file is modified.
```

"_calculates TreeHash checksum for file and compares with one in Journal_", "_file is modified_" talks about one file. "_Uploads modified files_" talks about uploading modified files.

so if you moved/renamed your file, it's a new file for `mtglacier`. there is no deduplication, cause I cannot modify metadata on server side, cannot do remote renames. (however if several files stored under same name I can tell where is new version, so I can do remote update of files)

Can I help more? Is there something that can be improved in current documentation?

**Comment by ihartley-zz** [comment]
Thanks.  All is clear - I just read it incorrectly.  I will compare treehashes before running mtglacier to remove duplicates (or create links).

Thanks again!  Ian.

**Comment by vsespb** [comment]
> or create links

note that it does not store symlinks/hardlinks as a links. it resolves links and stores it as separate files :(
