### ISSUE TITLE
Bandwidth throttling?

### ISSUE THREAD

**Issue by SiliconLunch** [vsespb/mt-aws-glacier#85]
I am wondering if mt-aws-glacier has any kind of bandwidth throttling implemented. An 80MB archive file took 4:38s to upload with "upload-file" command (approx. 300 KB/sec), whereas, using the Amazon RESTful APIs from Perl, the same file took 22s to upload (approx. 3.5MB/sec). I've repeated the experiment several times to eliminate transient network conditions. Any ideas as to why there is such a big difference?

**Comment by vsespb** [comment]
Hello. No bandwidth throttling.
When uploading see if you get HTTP 500 / HTTP 408 error messages. If you do, try decreaing `--concurrency` and `partsize`. Amazon servers timeouts (without a good reason) when see too slow and too big uploads.

From documentation:

`With high partsize*concurrency there is a risk of getting network timeouts HTTP 408/500.`

`concurrency (with sync, upload-file, restore, restore-completed commands) - number of parallel upload streams to run. (default 4)`

If you don't see it, that's strange. Well, to compare with other tools, you need use same concurrency and partsize. Usually concurrency is 1 and partsize can be different.

**Comment by SiliconLunch** [comment]
My partsize is set to 1GB (partsize=1024). So for an 80MB file, I expect only 1 part will be transmitted. 

I'll try again with concurrency = 1. And with smaller partsize.

Since the archive file < 4GB, the other tool I am experimenting with (Net::Amazon::Glacier) is able to upload it using the single upload_archive() primitive (not multi-part). Wonder if that also makes a difference with transmission speed.

**Comment by vsespb** [comment]
> Wonder if that also makes a difference with transmission speed.

yes, that should be too. but expect difference just few seconds (5-15s)

**Comment by vsespb** [comment]
also, check http vs https

**Comment by SiliconLunch** [comment]
Am using http currently, but will also test with https.

**Comment by SiliconLunch** [comment]
all the following combinations gave the same results (approx 4:30s):
partsize=1024 concurrency=4 protocol=http
partsize=1024 concurrency=1 protocol=http
partsize=16 concurrency=1 protocol=http

tried with https, but got connection timeouts.

**Comment by vsespb** [comment]
hm, that's strange - I don't see anything in Net::Amazon::Glacier that can make it faster.
could you pls post mtglacier output on console and all your options and config file (except `key` and `secret`) and snippet of Net::Amazon::Glacier code ?

Also does Net::Amazon::Glacier upload_archive returns true and archvie id ?

**Comment by vsespb** [comment]
Also, note that Net::Amazon::Glacier uses HTTPS
https://metacpan.org/source/TIM/Net-Amazon-Glacier-0.13/lib/Net/Amazon/Glacier.pm#L473

My current theory is: you are getting timeouts with https (in mtglacier), I expect you are getting it in Net::Amazon::Glacier too, but Net::Amazon::Glacier don't retry timeouts, it simply return false (meaning request failed), and you ignore this error.

**Comment by SiliconLunch** [comment]
FWIW, I have looked at the Net::Amazon::Glacier source code and confirm it is using https for the LWP::UserAgent requests. How much difference in throughput would you expect between http and https?

Not sure about the timeouts. Is there a diagnostic switch I can enable in mtglacier to see if this is happening?

Another reason I don't think it's timeouts is that the archive is actually successfully uploaded. A valid archive id is returned with both tools. I am also monitoring the network traffic out of my workstation, and in the case of mtglacier, it shows outbound traffic at 300 KB/sec for 4:30s, whereas for the Net::Amazon::Glacier script it confirms 3.5MB/sec for 22s.

I'll attach some console output next.

**Comment by SiliconLunch** [comment]
Net::Amazon::Glacier example console output:

```
bash-3.2$ ./glacier-upload-archive.pl NicoCloudVaults aws-java-sdk-1.8.5.zip
archive size: 80,742,136 bytes
Sun Jul 20 18:47:11 2014: creating Net::Amazon::Glacier object...
Sun Jul 20 18:47:11 2014: done

Sun Jul 20 18:47:11 2014: uploading [aws-java-sdk-1.8.5.zip] to vault [NicoCloudVaults]...
Sun Jul 20 18:47:34 2014:  archive id = posgNQFKXPRajqSss0lRH4kYh5I6Cs-CUAMhgdyaSz_7iPuNCeY5vuAW-egWiJ5kgR1CjgVfzQ1PeFVqsJ3ub6-NcQ8csG7vSZH9kfRrzjYN8anP2De7ZiLR_hpIFqk1sR8ud6QpI2Q]
Sun Jul 20 18:47:34 2014:  duration = 22s
Sun Jul 20 18:47:34 2014:  rate     = 3,528,854 bytes/sec
```

Net::Amazon::Glacier code:

```
#!/usr/bin/perl -s

use warnings;

use Data::Dumper;
use Net::Amazon::Glacier;
use Time::HiRes qw(gettimeofday);

our $debug;

sub tsprint;
sub tsprintf;
sub dprintf;

$USAGE = "usage: glacier-upload-archive.pl vault-name archive-path [description]\n";

$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0;

my ($vault_name, $archive_path, $description) = @ARGV;
die $USAGE unless $vault_name;
die $USAGE unless $archive_path;

my $size_bytes = -s $archive_path or die "$archive_path: $!\n";
printf "archive size: %s bytes\n", commas($size_bytes);

tsprint "creating Net::Amazon::Glacier object...\n";
my $glacier = Net::Amazon::Glacier->new(
    'us-west-1',
    'MYKEY',
    'MYSECRET',
    );
tsprint "done\n\n";

tsprintf "uploading [%s] to vault [%s]...\n", $archive_path, $vault_name;
my $t0 = gettimeofday();
my $archive_id = $glacier->upload_archive($vault_name, $archive_path, $description);
my $duration_secs = gettimeofday() - $t0;
tsprintf " archive id = p%s]\n", $archive_id;
tsprintf " duration = %s\n", convert_hms($duration_secs);
tsprintf " rate     = %s bytes/sec\n", commas(int($size_bytes / $duration_secs));

exit 0;
```

mtglacier example console output:

```
bash-3.2$ time /usr/local/bin/./mtglacier upload-file --config ~/glacier.cfg --dir "/Users/Nico/Desktop/Amazon AWS Glacier" --filename "/Users/Nico/Desktop/Amazon AWS Glacier/aws-java-sdk-1.8.5.zip"
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.115

PID 8433 Started worker
PID 8434 Started worker
PID 8435 Started worker
PID 8436 Started worker
PID 8433 Created an upload_id 1B_vJ0sWAfJwufSk9Au0fkd8BuhF3YrKV5pxsE1v_NOJPe6isn7eKg_RVJ_d3marSBuwBevGebb5zPMGsVX8Z1r3DToR
PID 8436 Uploaded part for aws-java-sdk-1.8.5.zip at offset [0]
PID 8435 Finished aws-java-sdk-1.8.5.zip hash [9cf534ec7fee75bcb374105d058e6af9fd21fca33d6d6c70957875af107ef11f] archive_id [s0o1MdkIugPxIpZS-UHKOAAbn2JUbmNjRvcUWjolrxZFdXz5-sQ-VNGvAhdDtPNaEC_uItnlbGLB4u9P4QdqNntqXgyY9_4ZVIWxVqPqDjTCq1lHr4X3Jp8D_UtXRDJFQG2oRf0VbA]
OK DONE

real    4m38.235s
user    0m2.372s
sys 0m0.922s
```

**Comment by vsespb** [comment]
> Not sure about the timeouts

there were no timeouts in your output. all ok.

here are my results:

(mtglacier, http, us-east-1)

```
$ time mtglacier upload-file --config glacier.cfg --dir "." --filename aws-sdk-java-master.zip --vault test1 -protocol http --journal j
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.115

PID 11603 Started worker
PID 11604 Started worker
PID 11605 Started worker
PID 11606 Started worker
PID 11604 Created an upload_id Zc42zVmspveuksAFTuB3bdDV6LvHcfU3DujoKi5nmwY-DroeQ3jjZywY6hlQE0zhQb0LNrSY1ra13OYRdL0qtCzKEOkg
PID 11606 Uploaded part for aws-sdk-java-master.zip at offset [0]
PID 11603 Finished aws-sdk-java-master.zip hash [810808a44daed41f26e0008a96ebe57297f764e00f32d1ebcba5689bcb080209] archive_id [8ANBGS1ZPvoyhYHwP5qr94L7o7CVD4H72v3xmXe3BpRO0qfhp0ECwLDfvCEQ0_psoiwZT9TLCeYAPzygzeks1c1_OFUtkBMKA-Rm8vivYCtXPeN-dw4y2DAtfYI7K4dgWbQsZZ0C5A]
OK DONE

real    3m26.860s
user    0m0.504s
sys 0m0.080s
```

(N:M:G, https, us-east-1)

```
time ./glacier-upload-archive.pl test1 aws-sdk-java-master.zip
archive size: 12820597 bytes
creating Net::Amazon::Glacier object...
done

uploading [aws-sdk-java-master.zip] to vault [test1]...
 archive id = p%s]
Tnwaf2Ug6DwGUgiGBLEwHV1p3sh_TGSrx7Kn_E2Rk2fE__SkFny4Lq8mA5ZIWIzf4TiwB51KvOk_VI7lL0lebu5IGq1njPf4aYMt3TMY_OogZ-ymgNKx3SfBwXK84ghTJRkBRzPTNw

real    3m28.033s
user    0m0.448s
sys 0m0.088s
```

(mtglacier, https, us-east-1)

```
$ time mtglacier upload-file --config glacier.cfg --dir "." --filename aws-sdk-java-master.zip --vault test1 -protocol https --journal j2
MT-AWS-Glacier, Copyright 2012-2014 Victor Efimov http://mt-aws.com/ Version 1.115

PID 11821 Started worker
PID 11822 Started worker
PID 11823 Started worker
PID 11824 Started worker
PID 11822 Created an upload_id p7SVIbfHyHEYhxEYseygD5-AwcOuq8cfTzIWaf9PoSLITgnWondkahZTfuSoFecxVeplzxTnLKxTc8zS0i5Q7RgUflCk
PID 11823 Uploaded part for aws-sdk-java-master.zip at offset [0]
PID 11821 Finished aws-sdk-java-master.zip hash [810808a44daed41f26e0008a96ebe57297f764e00f32d1ebcba5689bcb080209] archive_id [e2bJOyZG88U-2DnhbjFhyMo3GbTxuh5UuZFpegZSddn8VgpLK6TtN07Vn3LS38fq2sy0rIlMHsjG0R5Yb40Ic1vxz1XAheSIoJjjW_I98uccpRgWkIAg4l1y32qxPnm5-1SEXQxc1g]
OK DONE

real    3m29.658s
user    0m0.656s
sys 0m0.100s
```

note that I used `us-east-1` region.

also, I edited glacier-upload-archive (there were functions like `tsprint` - i think part of 3rd party libs, I dont have it on my system):

```
#!/usr/bin/perl -s

use warnings;

use Data::Dumper;
use Net::Amazon::Glacier;
use Time::HiRes qw(gettimeofday);

our $debug;

#sub tsprint;
#sub tsprintf;
#sub dprintf;

$USAGE = "usage: glacier-upload-archive.pl vault-name archive-path [description]\n";

$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0;

my ($vault_name, $archive_path, $description) = @ARGV;
die $USAGE unless $vault_name;
die $USAGE unless $archive_path;

my $size_bytes = -s $archive_path or die "$archive_path: $!\n";
printf "archive size: %s bytes\n", $size_bytes;

print "creating Net::Amazon::Glacier object...\n";
my $glacier = Net::Amazon::Glacier->new(
    'us-east-1',
    'key',
    'secret',
    );
print "done\n\n";

printf "uploading [%s] to vault [%s]...\n", $archive_path, $vault_name;
my $t0 = gettimeofday();
my $archive_id = $glacier->upload_archive($vault_name, $archive_path, $description);
my $duration_secs = gettimeofday() - $t0;
print " archive id = p%s]\n", $archive_id, "\n";

exit 0;
```

so in my case time looks almost same.

I think you should try both in smae mode - HTTPS. You told `tried with https, but got connection timeouts.` - that's strange too, there can be timeouts indeed, but you should see it for both scripts at same time. anyway that is different kind of strangeness. could you pls post `mtglacier` output in https mode (with `time` prefix)? need so see those timeouts

**Comment by SiliconLunch** [comment]
I had problems with HTTPS due to my platform - OS X v10.9.2. I had to set an environment variable PERL_LWP_SSL_VERIFY_HOSTNAME=0 to work around the error message "Can't verify SSL peers without knowing which Certificate Authorities to trust".

Maybe the throughput issue is also due to the platform. Will run some more tests when I have time.

The last point to note was that I tried uploading an archive several times with my Net::Amazon::Glacier script and several times with mtglacier. When I checked the Glacier vault inventory the next day, only the uploads done via Net::Amazon::Glacier had succeeded (ie, were in the vault). None of the attempts to upload via mtglacier had succeeded, however, no errors were reported by mtglacier after the uploads. Very strange.

**Comment by vsespb** [comment]
PERL_LWP_SSL_VERIFY_HOSTNAME will work for glacier-upload-archive.pl, but will not work for mtglacier - mtglacier explicitly sets verify_hostname to 1 (see https://metacpan.org/source/MSCHILLI/libwww-perl-6.08/lib/LWP/UserAgent.pm#L35 ) to make application secure and this is priority over PERL_LWP_SSL_VERIFY_HOSTNAME

I think mtglacier probably will not properly detect error "Can't verify SSL peers without knowing which Certificate Authorities to trust" and can treat it as HTTP 500 and retry requests. Thus it will end with 100 retries and exit.

I just have another user reported that certificates are broken on OXS 10.9 #87 (however he uses local::lib which can be root of issue).
Probably need to update LWP::UserAgent, LWP::Protocol::https and update Mozilla::CA to latest versions. But I don't have OSX so I am not sure how to reproduce this deploy problem.

So problem with upload speed is same now - you're comparing apples and oranges. Need compare in same mode, not  http vs https.

**Comment by vsespb** [comment]
It's explicitly documented in LWP::UserAgent that PERL_LWP_SSL_VERIFY_HOSTNAME not always work: 

https://metacpan.org/pod/LWP::UserAgent#verify_hostname-bool

```
verify_hostname => $bool

[cut]

    This option is initialized from the PERL_LWP_SSL_VERIFY_HOSTNAME environment variable. If this environment variable isn't set; then verify_hostname defaults to 1.
```

so trying to use PERL_LWP_SSL_VERIFY_HOSTNAME with script without checking its code is not reliable.

two things can be interesting in this ticket:

1) comparing speed in same, HTTPS mode
2) investigation of deploy problems (how come Mozilla::CA cert file is broken)

**Comment by vsespb** [comment]
> 2) investigation of deploy problems (how come Mozilla::CA cert file is broken)

in a different ticket I investigated deploy problem in OSX 10.9 https://github.com/vsespb/mt-aws-glacier/issues/87#issuecomment-50241736 tl;dr - just update LWP::UserAgent and install LWP::Protocol::https via CPAN

**Comment by vsespb** [comment]
> just update LWP::UserAgent and install LWP::Protocol::https via CPAN

and install Mozilla::CA

**Comment by vsespb** [comment]
FYI Version 1.116 released, it will raise sane error if HTTPS support on MacOSX broken (instead of timeouts).

**Comment by vsespb** [comment]
Closing for now due to inactivity. Let me know if you have any proof of problem, I will reopen then.
