### ISSUE TITLE
Request signature mismatch 

### ISSUE THREAD

**Issue by tpdinh** [vsespb/mt-aws-glacier#9]
Hi,

I'm trying the newer version (0.75 beta) to download some files and got this signature mismatch error. The older version is working fine for the same command. Note that the files were uploading using the older version.

MT-AWS-Glacier, part of MT-AWS suite, Copyright (c) 2012  Victor Efimov http://mt-aws.com/ Version 0.74beta
PID 30845 Started worker
PID 30846 Started worker
PID 30847 Started worker
PID 30848 Started worker
Error:
POST http://glacier.us-east-1.amazonaws.com/-/vaults/TA/jobs

 Signature=a361e4836c5408f87935cc805234ede97ef41ac56182888b5bff0e676752f2ac
Host: glacier.us-east-1.amazonaws.com
User-Agent: mt-aws-glacier/0.74beta (http://mt-aws.com/) libwww-perl/5.833
Content-Length: 191
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20121116T201753Z
X-Amz-Glacier-Version: 2012-06-01

{
  "Type": "archive-retrieval",
  "ArchiveId": "1mAFFVTVymMS50YLEhbfKh-czVlg8-rLeKY-H_7bLOL2nh9-Wo9Xv0zvQgt7I40XlBZmCaVo-mkX_Nv-WBHzrur5vzdbZPJwILjDAG9RlA3W3is3R_peimaW3JHuRrUjVCc1_btrug"
}\n
HTTP/1.1 403 Forbidden
Date: Fri, 16 Nov 2012 20:17:53 GMT
Content-Length: 800
Content-Type: application/json
Client-Date: Fri, 16 Nov 2012 20:17:53 GMT
Client-Peer: 72.21.195.182:80
Client-Response-Num: 1
X-Amzn-RequestId: OPJaeYQ8vIKudljdzghJueux53F0WpRKF1YlEnXG-qSIl2Q

{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/-/vaults/TA/jobs\n\ncontent-type:application/x-www-form-urlencoded; charset=utf-8\nhost:glacier.us-east-1.amazonaws.com\nx-amz-date:20121116T201753Z\nx-amz-glacier-version:2012-06-01\n\ncontent-type;host;x-amz-date;x-amz-glacier-version\n361acdfa41b281d2...
(+ 288 more bytes not shown)

PARENT Exit

**Comment by vsespb** [comment]
Ok, thanks for reporting. I commited fix to development branch.
I need to test it with full sync-retrieve-download cycle. (thus I need to wait 4 hour Glacier retrieve process). After that, tomorrow, I will release new version to master branch and notify you.

**Comment by tpdinh** [comment]
Great. Looking forward to hearing from you. It would be great if you can 
provide what is causing it.

**Comment by vsespb** [comment]
Fixed - I released a fix 0.75beta now (bug was in 0.74beta).
Bug was caused by SHA256 optimization in 0.74beta when calculating signature (see ChangeLog)
It does not affect in any way your files stored in glacier.
