### ISSUE TITLE
how to restore a particular file from amazon glacier

### ISSUE THREAD

**Issue by abhishek6590** [vsespb/mt-aws-glacier#97]
Hi,

Please tell me how to restore a particular file uploaded o amazon glacier. Please mention which command i can use for this.

Thanks.

**Comment by vsespb** [comment]
https://github.com/vsespb/mt-aws-glacier#restore
https://github.com/vsespb/mt-aws-glacier#restore-completed
https://github.com/vsespb/mt-aws-glacier#file-selection-options

**Comment by abhishek6590** [comment]
Hi,

Thanks for your quick response. can you please check the command -

./mtglacier restore --config glacier.cfg --dir /home/backup --filter '+myfile.gz +' --vault abfile --journal journal.log --max-number-of-files 1

is it right?

**Comment by vsespb** [comment]
`--filter '+myfile.gz +'` will filter all files actually. I am not sure `--max-number-of-files 1` will help here,
as filtering does not imply order of files.

Instead try `--filter '+myfile.gz -'`.

Try the command with `--dry-run` option first.

**Comment by abhishek6590** [comment]
Hi,

ok i will try it with --dry-run option. it is showing error if i am not using --max-number-of-files.

As i uploaded many files on glacier for example myfile.gz, myfile1.gz, myfile2.gz and i only want to restore myfile.gz right now. in this case --filter '+myfile.gz -' will work?

**Comment by abhishek6590** [comment]
or i need to mention --filter '+archived id -' .

**Comment by vsespb** [comment]
> in this case --filter '+myfile.gz -' will work?

yes, but try with `--dry-run` first

**Comment by abhishek6590** [comment]
It works. thanks a lot. :+1:
