### ISSUE TITLE
issue while using restore complete

### ISSUE THREAD

**Issue by mark23450** [vsespb/mt-aws-glacier#99]
Hi,

I am not able to download files from glacier while using following command.

./mtglacier restore-completed --config glacier.cfg --dry-run  --dir /home/mark/ --filter '+markdata1.gz -' --vault mark --journal journal.log

It is showing "Will DOWNLOAD (if available)"
OK done

It is almost more than 8 hours when i requested restore command.

Please check this.

Thanks.

**Comment by vsespb** [comment]
You use `--dry-run` - that will only should what you going to do. Remove `--dry-run`

**Comment by mark23450** [comment]
After removing --dry-run it is also not downloading. It is showing- 

PID 17705 Started worker
PID 17706 Started worker
PID 17707 Started worker
PID 17708 Started worker
PID 17706 Retrieved Job List
OK DONE

but when i am not mentioning --filter option for particular file it is downloading a file . But i only want to download a particular file. So i have to use this option. Please tell me what to do.

Thanks.

**Comment by vsespb** [comment]
Maybe you `restore`'d wrong file

**Comment by mark23450** [comment]
i am using this command 

./mtglacier restore --config glacier.cfg --dry-run --dir /home/mark/ --filter '+markdata1.gz -' --vault mark --journal journal.log  --max-number-of-files 1

and restoring the right file available in journal.log

**Comment by vsespb** [comment]
Maybe you did not run it without `dry-run` too?

**Comment by mark23450** [comment]
should i need to run restore command without --dry-run.

**Comment by vsespb** [comment]
https://github.com/vsespb/mt-aws-glacier#additional-command-line-options

```
dry-run (with sync, purge-vault, restore, restore-completed and even check-local-hash commands) - do 
not perform actual work, print what will happen instead.
```

**Comment by mark23450** [comment]
yes. that is i am saying. it should not affect on command. Then why file is not downloading.

**Comment by vsespb** [comment]
no, it's saying that "do not perform actual work" "print what will happen instead".

i.e command ran with `--dry-run` will not do anything, except printing to the screen.

it's pretty common name for such option http://en.wikipedia.org/wiki/Dry_run_%28testing%29
http://en.wiktionary.org/wiki/dry_run

**Comment by mark23450** [comment]
Ohhh. Okay. Let me check without --dry-run
